Repository instadeepai/Mava, pull requests merged in 2021-07, with the labels that each got.

#271 Feature/Enforce docstring code coverage.
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  pyproject.toml
  setup.py
Labels: documentation

#258 Feature/Improve Mava agent networks
  .github/workflows/ci.yaml
  examples/debugging/simple_spread/feedforward/centralised/run_mad4pg.py
  examples/debugging/simple_spread/feedforward/centralised/run_maddpg.py
  examples/debugging/simple_spread/feedforward/centralised/run_mappo.py
  examples/debugging/simple_spread/feedforward/networked/run_maddpg.py
  examples/debugging/simple_spread/feedforward/networked/run_maddpg_custom_network.py
  examples/debugging/simple_spread/feedforward/state_based/run_mad4pg.py
  examples/debugging/simple_spread/feedforward/state_based/run_maddpg.py
  examples/debugging/simple_spread/recurrent/state_based/run_maddpg.py
  examples/quickstart.ipynb
  examples/smac/recurrent/decentralised/run_madqn.py
  mava/components/tf/architectures/centralised.py
  mava/components/tf/architectures/decentralised.py
  mava/components/tf/architectures/networked.py
  mava/components/tf/architectures/state_based.py
  mava/components/tf/modules/stabilising/fingerprints.py
  mava/systems/tf/dial/builder.py
  mava/systems/tf/dial/execution.py
  mava/systems/tf/dial/networks.py
  mava/systems/tf/dial/system.py
  mava/systems/tf/dial/training.py
  mava/systems/tf/executors.py
  mava/systems/tf/mad4pg/execution.py
  mava/systems/tf/mad4pg/networks.py
  mava/systems/tf/mad4pg/system.py
  mava/systems/tf/mad4pg/training.py
  mava/systems/tf/maddpg/builder.py
  mava/systems/tf/maddpg/execution.py
  mava/systems/tf/maddpg/networks.py
  mava/systems/tf/maddpg/system.py
  mava/systems/tf/maddpg/training.py
  mava/systems/tf/madqn/__init__.py
  mava/systems/tf/madqn/builder.py
  mava/systems/tf/madqn/execution.py
  mava/systems/tf/madqn/networks.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/madqn/training.py
  mava/systems/tf/mappo/builder.py
  mava/systems/tf/mappo/execution.py
  mava/systems/tf/mappo/networks.py
  mava/systems/tf/mappo/system.py
  mava/systems/tf/mappo/training.py
  mava/systems/tf/qmix/builder.py
  mava/systems/tf/qmix/execution.py
  mava/systems/tf/qmix/networks.py
  mava/systems/tf/qmix/system.py
  mava/systems/tf/qmix/training.py
  mava/systems/tf/vdn/builder.py
  mava/systems/tf/vdn/execution.py
  mava/systems/tf/vdn/networks.py
  mava/systems/tf/vdn/system.py
  mava/systems/tf/vdn/training.py
  mava/wrappers/system_trainer_statistics.py
  tests/networks/networks_test.py
  tests/systems/maddpg_system_test.py
  tests/systems/madqn_system_test.py
  tests/systems/mappo_system_test.py
Labels: enhancement

#273 Chore/Updated makefile and readme for Windows.
  Makefile
  README.md
Labels: bug

#275 feature: working version of importance sampling on feedforward madqn.
  examples/debugging/simple_spread/feedforward/decentralised/run_madqn.py
  examples/flatland/feedforward/decentralised/run_madqn.py
  examples/petting_zoo/atari/pong/feedforward/decentralised/run_madqn.py
  examples/smac/feedforward/decentralised/run_madqn.py
  mava/systems/tf/madqn/builder.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/madqn/training.py
  mava/systems/tf/qmix/builder.py
  mava/systems/tf/qmix/system.py
  mava/systems/tf/vdn/builder.py
  mava/systems/tf/vdn/system.py
  mava/wrappers/__init__.py
  mava/wrappers/system_trainer_statistics.py
Labels: enhancement
