Repository instadeepai/Mava, pull requests merged in 2021-08, with the labels that each got.

#288 Bugfix: Simple_spread observation code.
  mava/utils/debugging/scenarios/simple_spread.py
Labels: bug

#296 Feature/mava reproducibility and PZ wrapper fix
  .github/workflows/ci.yaml
  examples/quickstart.ipynb
  examples/smac/recurrent/decentralised/run_madqn.py
  mava/adders/reverb/base.py
  mava/components/tf/losses/sequence.py
  mava/components/tf/networks/__init__.py
  mava/components/tf/networks/continuous.py
  mava/systems/tf/dial/networks.py
  mava/systems/tf/mad4pg/networks.py
  mava/systems/tf/maddpg/networks.py
  mava/systems/tf/madqn/networks.py
  mava/systems/tf/mappo/networks.py
  mava/systems/tf/mappo/training.py
  mava/systems/tf/qmix/networks.py
  mava/systems/tf/qmix/system.py
  mava/systems/tf/vdn/networks.py
  mava/systems/tf/vdn/system.py
  mava/utils/debugging/make_env.py
  mava/utils/debugging/scenarios/simple_spread.py
  mava/utils/environments/debugging_utils.py
  mava/utils/environments/flatland_utils.py
  mava/utils/wrapper_utils.py
  mava/wrappers/flatland.py
  mava/wrappers/pettingzoo.py
  pyproject.toml
  setup.py
  tests/adders/adders_utils.py
  tests/adders/episode_adders_test.py
  tests/adders/episode_adders_test_data.py
  tests/adders/sequence_adders_test.py
  tests/adders/transition_adders_test.py
  tests/adders/transition_adders_test_data.py
  tests/networks/networks_test.py
  tests/utils/environment_utils_test.py
  tests/wrappers/wrapper_test.py
Labels: bug

#299 Feature: Add Readme for setting up a new environment
  README.md
  mava/wrappers/README.md
Labels: enhancement

#301 Add checkpoint save interval variable.
  mava/systems/tf/dial/builder.py
  mava/systems/tf/dial/system.py
  mava/systems/tf/dial/training.py
  mava/systems/tf/mad4pg/system.py
  mava/systems/tf/mad4pg/training.py
  mava/systems/tf/maddpg/builder.py
  mava/systems/tf/maddpg/system.py
  mava/systems/tf/maddpg/training.py
  mava/systems/tf/madqn/builder.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/madqn/training.py
  mava/systems/tf/mappo/builder.py
  mava/systems/tf/mappo/system.py
  mava/systems/tf/mappo/training.py
  mava/systems/tf/qmix/builder.py
  mava/systems/tf/qmix/system.py
  mava/systems/tf/qmix/training.py
  mava/systems/tf/vdn/builder.py
  mava/systems/tf/vdn/system.py
  mava/systems/tf/vdn/training.py
Labels: enhancement

#304 Chore/flatland gif
  README.md
  docs/images/flatland.gif
Labels: documentation
