Repository instadeepai/Mava, pull requests merged in 2022-10, with the labels that each got.

#772 fix: Python 3.7 checker issue.
  setup.py
Labels: bug, size/XS

#759 Feature: PettingZoo agent ids.
  examples/README.md
  examples/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_ippo.py
  mava/systems/executor.py
  mava/utils/environments/flatland_utils.py
  mava/utils/environments/pettingzoo_utils.py
  mava/utils/environments/smac_utils.py
Labels: enhancement, benchmark, size/S

#770 Feature/Termination Function
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_grid_search.py
  mava/components/building/distributor.py
  mava/components/building/environments.py
  mava/components/updating/terminators.py
  mava/systems/launcher.py
  mava/systems/system.py
  mava/utils/lp_utils.py
  mypy.ini
  tests/components/updating/terminators_test.py
Labels: enhancement, size/L

#786 update benchmarking labels
  .github/workflows/push_docker.yaml
Labels: maintenance, size/XS

#774 Feature/code coverage badge
  .coveragerc
  .github/workflows/ci.yaml
  .github/workflows/ci_main.yaml
  README.md
  bash_scripts/local_tests.sh
  bash_scripts/tests.sh
Labels: documentation, size/M

#742 Implemented target value normalization during training in the IPPO sy…
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_value_norm.py
  mava/components/training/advantage_estimation.py
  mava/components/training/base.py
  mava/components/training/model_updating.py
  mava/components/training/step.py
  mava/utils/jax_training_utils.py
  tests/components/training/step_test.py
  tests/components/training/value_normalisation_test.py
Labels: size/L, benchmark complete

#769 feat: death masking in SMAC
  examples/smac/feedforward/decentralised/run_ippo_smac_death_masking.py
  mava/utils/environments/smac_utils.py
  mava/wrappers/smac.py
Labels: enhancement, size/L, benchmark complete

#790 Update codeowners list
  .github/CODEOWNERS
Labels: maintenance, size/XS

#794 fix: remove integrity check
  bash_scripts/tests.sh
Labels: bug, size/XS

#781 Feature: Orthogonal Networks Initialisation.
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_othogonal_network_init.py
  mava/systems/ippo/networks.py
  tests/integration/networks_test.py
Labels: enhancement, size/L, benchmark complete

#779 Feature/Enviroment loop v2
  .github/workflows/push_docker.yaml
  DETAILED_INSTALL.md
  Dockerfile
  Makefile
  README.md
  docs/environments/open_spiel.md
  mava/__init__.py
  mava/environment_loop.py
  mava/environment_loops/open_spiel_environment_loop.py
  mava/utils/environments/open_spiel_utils.py
  mava/utils/environments/pettingzoo_utils.py
  mava/utils/wrapper_utils.py
  mava/wrappers/README.md
  mava/wrappers/__init__.py
  mava/wrappers/env_preprocess_wrappers.py
  mava/wrappers/env_wrappers.py
  mava/wrappers/environment_loop_wrappers.py
  mava/wrappers/open_spiel.py
  mava/wrappers/pettingzoo.py
  tests/components/building/networks_test.py
  tests/conftest.py
  tests/enums.py
  tests/environment_loops/environment_loop_test.py
  tests/jax/mocks.py
  tests/mocks.py
  tests/systems/ippo_system_evaluation_test.py
  tests/systems/systems_test_data.py
  tests/test_utils/test_data.py
  tests/test_utils/utils_test.py
  tests/wrappers/wrapper_test.py
Labels: enhancement, maintenance, size/XXL

#800 fix: smac action selection bug
  mava/wrappers/smac.py
Labels: bug, size/XS

#792 feat: sum return feature
  examples/README.md
  examples/petting_zoo/simple_spread/feedforward/decentralised/run_ippo.py
  mava/wrappers/environment_loop_wrappers.py
Labels: enhancement, priority/high, size/L

#787 Feature/observations value normalisation
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_value_norm.py
  mava/components/building/parameter_client.py
  mava/components/training/advantage_estimation.py
  mava/components/training/base.py
  mava/components/training/model_updating.py
  mava/components/training/step.py
  mava/components/training/trainer.py
  mava/components/updating/parameter_server.py
  mava/constants.py
  mava/systems/executor.py
  mava/utils/jax_training_utils.py
  tests/components/building/parameter_client_test.py
  tests/components/training/step_test.py
  tests/components/training/trainer_test.py
  tests/components/training/value_normalisation_test.py
  tests/components/updating/parameter_server_test.py
  tests/core_system_components/executor_test.py
  tests/integration/parameter_server_test.py
  tests/integration/trainer_test.py
  tests/systems/systems_test_data.py
Labels: priority/high, size/XL, benchmark complete

#805 fixed bug with target value normalisation when value clip is true
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_value_norm.py
  mava/components/training/losses.py
  mava/components/training/step.py
  mava/utils/jax_training_utils.py
Labels: benchmark in progress, size/S

#806 Feature/new logo
  README.md
  docs/images/new_logo.png
  docs/images/new_logo_name.png
Labels: documentation, size/XS

#808 Maintain: evaluation set based on executor or evaluator.
  mava/components/building/environments.py
  tests/components/building/environments_test.py
Labels: maintenance, size/XS

#813 Remove SwitchGame and TwoStep environments
  mava/utils/debugging/environments/__init__.py
  mava/utils/debugging/environments/switch_game.py
  mava/utils/debugging/environments/two_step.py
  mava/utils/environments/debugging_utils.py
  mava/wrappers/__init__.py
  mava/wrappers/debugging_envs.py
Labels: maintenance, size/L

#799 feat: Terminate experiment in case of error
  mava/components/building/distributor.py
  mava/components/updating/parameter_server.py
  mava/core_jax.py
  mava/environment_loop.py
  mava/systems/parameter_client.py
  mava/systems/trainer.py
  tests/components/updating/parameter_server_test.py
  tests/core_system_components/trainer_test.py
  tests/integration/evaluator_test.py
  tests/integration/executor_test.py
  tests/integration/parameter_server_test.py
Labels: enhancement, priority/high, size/L

#816 Bugfix: environment concatenation wrappers
  mava/wrappers/env_preprocess_wrappers.py
Labels: size/M

#815 Bugfix/pettingzoo agent id concatenation
  mava/utils/environments/pettingzoo_utils.py
  mava/wrappers/env_preprocess_wrappers.py
Labels: bug, size/S
