Repository instadeepai/Mava, pull requests merged in 2022-07, with the labels that each got.

#579 Tests/jax components/adders
  mava/components/jax/building/__init__.py
  mava/components/jax/building/adders.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/distributor.py
  mava/systems/jax/launcher.py
  mava/systems/jax/mappo/system.py
  mava/utils/builder_utils.py
  tests/jax/components/building/adders_test.py
  tests/jax/mocks.py
  tests/tf/adders/adders_utils.py
  tests/tf/adders/episode_adders_test.py
  tests/tf/adders/sequence_adders_test.py
  tests/tf/adders/transition_adders_test.py
Labels: size/XL

#577 Test/components/losses
  tests/jax/components/training/losses_test.py
Labels: size/L

#598 test: Tests Jax distributor components
  tests/jax/components/building/distributor_test.py
Labels: size/L

#610 feat: split trainer init into multiple components.
  mava/components/jax/training/__init__.py
  mava/components/jax/training/trainer.py
  mava/systems/jax/mappo/system.py
Labels: size/L

#618 Feature/local testing script
  Makefile
  bash_scripts/local_tests.sh
Labels: size/M

#601 Maintain/env specs names
  Makefile
  examples/tf/quickstart.ipynb
  mava/adders/reverb/episode.py
  mava/adders/reverb/sequence.py
  mava/adders/reverb/transition.py
  mava/adders/reverb/utils.py
  mava/components/jax/building/adders.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/environments.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/system_init.py
  mava/components/tf/architectures/decentralised.py
  mava/components/tf/architectures/state_based.py
  mava/specs.py
  mava/systems/jax/mappo/components.py
  mava/systems/jax/mappo/networks.py
  mava/systems/tf/maddpg/builder.py
  mava/systems/tf/maddpg/networks.py
  mava/systems/tf/madqn/builder.py
  mava/systems/tf/madqn/networks.py
  mava/systems/tf/mappo/builder.py
  mava/systems/tf/mappo/networks.py
  mava/systems/tf/value_decomposition/networks.py
  mava/utils/environments/RoboCup_env/robocup_utils/agent.py
  mava/utils/environments/RoboCup_env/robocup_utils/util_functions.py
  mava/wrappers/debugging_envs.py
  mava/wrappers/flatland.py
  mava/wrappers/meltingpot.py
  mava/wrappers/open_spiel.py
  mava/wrappers/pettingzoo.py
  mava/wrappers/smac.py
  tests/jax/components/building/adders_test.py
  tests/jax/components/building/networks_test.py
  tests/jax/mocks.py
  tests/tf/adders/adders_utils.py
  tests/tf/conftest.py
  tests/tf/mocks.py
  tests/tf/wrappers/wrapper_test.py
Labels: size/XL

#581 Feature/add sampler remover components
  mava/components/jax/building/data_server.py
  mava/components/jax/building/rate_limiters.py
  mava/components/jax/building/reverb_components.py
  tests/jax/components/building/data_server_test_data.py
  tests/jax/mocks.py
Labels: size/L

#621 chore: better store name for env spec
  mava/components/jax/building/data_server.py
  mava/components/jax/building/environments.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/system_init.py
  mava/systems/jax/mappo/components.py
  tests/jax/components/building/networks_test.py
  tests/jax/mocks.py
Labels: size/M

#597 Test/rate limiters
  tests/jax/components/building/reverb_components_test.py
Labels: size/L

#617 Test/jax environments
  tests/jax/components/building/environments_test.py
Labels: size/L

#615 feat: core config test
  tests/jax/core_system_components/config_test.py
Labels: size/L

#622 tests: data server component unit tests
  tests/jax/components/building/data_server_test.py
  tests/jax/integration/__init__.py
  tests/jax/integration/data_server_test.py
  tests/jax/integration/data_server_test_data.py
Labels: size/L

#606 Tests/jax component/training/model updating
  mava/components/jax/training/model_updating.py
  tests/jax/components/training/model_updating_test.py
Labels: size/L

#624 test: parameter client unit test
  tests/jax/components/building/parameter_client_test.py
Labels: size/L

#613 Test/core executor
  tests/jax/core_system_components/executor_test.py
  tests/jax/core_system_components/parameter_server_test.py
  tests/jax/integration/__init__.py
  tests/jax/integration/executor_test.py
  tests/jax/integration/parameter_server_test.py
  tests/jax/mocks.py
Labels: size/XL

#627 Test/jax core parameter client unit tests
  mava/systems/jax/parameter_client.py
  tests/jax/components/building/parameter_client_test.py
  tests/jax/core_system_components/parameter_client_test.py
Labels: size/L

#611 test: testing launcher class for Jax-based Mava systems
  tests/jax/core_system_components/launcher_test.py
Labels: size/L

#632 Tests/core system unit tests
  tests/jax/core_system_components/system_component_test.py
Labels: size/L

#655 Feature/readme fix
  README.md
Labels: size/XS
