Repository instadeepai/Mava, pull requests merged in 2022-04, with the labels that each got.

#470 fix: Update black version.
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  mava/wrappers/open_spiel.py
  mava/wrappers/pettingzoo.py
  pyproject.toml
  setup.py
Labels: size/S

#483 Feature/Only init component once.
  mava/components/jax/building/adders.py
  mava/components/jax/building/adders_test.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/datasets.py
  mava/components/jax/building/distributor.py
  mava/components/jax/building/environments.py
  mava/components/jax/building/loggers.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/parameter_client.py
  mava/components/jax/component.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/executing/base.py
  mava/components/jax/executing/observing.py
  mava/components/jax/training/advantage_estimation.py
  mava/components/jax/training/base.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/components/jax/updating/parameter_server.py
  mava/systems/jax/config.py
  mava/systems/jax/mappo/components.py
  mava/systems/jax/system.py
  mava/systems/jax/system_test.py
  mava/testing/building/mocks.py
Labels: size/L

#459 Feat/maddpg obs optim
  mava/systems/tf/mad4pg/networks.py
  mava/systems/tf/maddpg/networks.py
  mava/systems/tf/maddpg/training.py
Labels: benchmark, size/S

#475 feat: Add fixed sampler capability + bugfixes
  examples/tf/debugging/simple_spread/feedforward/decentralised/run_maddpg_scale_trainers_fixed_nets.py
  mava/systems/tf/mad4pg/execution.py
  mava/systems/tf/mad4pg/system.py
  mava/systems/tf/maddpg/builder.py
  mava/systems/tf/maddpg/execution.py
  mava/systems/tf/maddpg/system.py
Labels: enhancement, size/L

#477 Feature/fix sampler madqn
  mava/systems/tf/madqn/builder.py
  mava/systems/tf/madqn/execution.py
  mava/systems/tf/madqn/networks.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/mappo/builder.py
Labels: size/M

#485 chore: Up the patch version of mava - 0.1.3.
  mava/_metadata.py
Labels: size/XS

#490 fix: Fix parameter_client and batch_size in trainer component.
  mava/components/jax/building/datasets.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/systems/jax/parameter_client.py
Labels: bug, benchmark, size/S
