Repository instadeepai/Mava, pull requests merged in 2022-03, with the labels that each got.

#444 Mainetenance: Fix tf examples issues
  examples/README.md
  examples/tf/petting_zoo/sisl/multiwalker/feedforward/decentralised/run_mappo.py
Labels: documentation, size/XS

#428 fix: shared weights with agent type
  mava/systems/tf/maddpg/system.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/mappo/system.py
Labels: bug, size/M

#446 Fix broken readme links and neaten up formatting
  examples/README.md
Labels: documentation, size/M

#433 Feature/jax abstract builder class
  mava/core_jax.py
  mava/core_jax_test.py
Labels: enhancement, size/M

#458 Bugfix/Mypy Inconsistency Issue
  setup.py
Labels: size/XS

#456 fix/remove flatland wrapper debug print statement
  mava/wrappers/flatland.py
Labels: size/XS

#461 Feature/new issue template for investigations
  .github/ISSUE_TEMPLATE/investigation_internal.md
Labels: size/S

#460 Bugfix/MADD(4)PG
  examples/tf/petting_zoo/sisl/multiwalker/recurrent/decentralised/run_mad4pg.py
  mava/adders/reverb/base.py
  mava/systems/tf/mad4pg/training.py
  mava/systems/tf/maddpg/execution.py
  mava/systems/tf/maddpg/training.py
Labels: bug, enhancement, size/L

#464 Feat/Upped pypi version.
  mava/_metadata.py
Labels: size/XS

#466 Bugfix/ Release aren't triggering pypi push job.
  .github/workflows/release.yaml
  mava/systems/tf/mappo/networks.py
  mava/utils/environments/open_spiel_utils.py
  mava/utils/environments/pettingzoo_utils.py
  mava/utils/wrapper_utils.py
  mava/wrappers/env_preprocess_wrappers.py
  mava/wrappers/environment_loop_wrappers.py
Labels: size/S

#467 Feature / Release 0.1.2 v2
  .github/workflows/release.yaml
  mava/systems/tf/mappo/networks.py
  mava/utils/environments/open_spiel_utils.py
  mava/utils/environments/pettingzoo_utils.py
  mava/utils/wrapper_utils.py
  mava/wrappers/env_preprocess_wrappers.py
  mava/wrappers/environment_loop_wrappers.py
Labels: size/S
