Repository instadeepai/Mava, pull requests merged in 2022-09, with the labels that each got.

#712 Feature: Make separate networks ippo build from shared networks ippo.
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_sep_networks.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_with_monitoring.py
  examples/jax/flatland/feedforward/decentralised/run_ippo.py
  examples/jax/smac/feedforward/decentralised/run_ippo.py
  examples/jax/smac/feedforward/decentralised/run_ippo_sep_networks.py
  mava/components/jax/building/parameter_client.py
  mava/specs.py
  mava/systems/jax/ippo/system.py
  mava/systems/tf/madqn/builder.py.isorted
  tests/jax/components/building/networks_test.py
  tests/jax/systems/systems_test_data.py
Labels: Maintenance, size/L

#717 Fix update period
  examples/jax/quickstart.ipynb
  mava/components/jax/building/parameter_client.py
  mava/systems/tf/mad4pg/system.py
  mava/systems/tf/maddpg/builder.py
  mava/systems/tf/maddpg/system.py
  mava/systems/tf/madqn/builder.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/mappo/builder.py
  mava/systems/tf/mappo/system.py
  tests/jax/components/building/parameter_client_test.py
  tests/jax/integration/builder_test.py
  tests/jax/mocks.py
  tests/jax/systems/systems_test_data.py
  tests/tf/systems/qmix_system_test.py
Labels: enhancement, size/M

#716 Maintain/readme updates
  DETAILED_INSTALL.md
  OPTIONAL_INSTALL.md
  README.md
  mava/wrappers/README.md
Labels: documentation, size/XL

#725 Fix: Provide unique rng keys to each process
  mava/components/jax/building/distributor.py
  mava/components/jax/building/networks.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/systems/jax/builder.py
  tests/jax/components/building/data_server_test.py
  tests/jax/components/building/distributor_test.py
  tests/jax/components/building/networks_test.py
  tests/jax/components/executing/action_selection_test.py
  tests/jax/components/training/losses_test.py
  tests/jax/components/training/step_test.py
  tests/jax/components/training/trainer_test.py
  tests/jax/core_system_components/builder_test.py
  tests/jax/integration/builder_test.py
  tests/jax/integration/data_server_test.py
  tests/jax/mocks.py
Labels: size/L

#721 Feature/jit action selection across agents
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/networks/__init__.py
  mava/components/jax/networks/distributional.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/systems/jax/executor.py
  mava/systems/jax/ippo/networks.py
  mava/systems/jax/trainer.py
  mava/utils/environments/debugging_utils.py
  mava/utils/environments/flatland_utils.py
  mava/utils/environments/smac_utils.py
  mava/utils/jax_training_utils.py
  mypy.ini
  tests/jax/components/executing/action_selection_test.py
  tests/jax/components/training/losses_test.py
  tests/jax/components/training/model_updating_test.py
  tests/jax/components/training/step_test.py
Labels: benchmark, size/L

#741 Feature/remove shared networks
  docs/create_system.md
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_sep_networks.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_with_monitoring.py
  examples/jax/flatland/feedforward/decentralised/run_ippo.py
  examples/jax/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_ippo.py
  examples/jax/quickstart.ipynb
  examples/jax/smac/feedforward/decentralised/run_ippo.py
  examples/jax/smac/feedforward/decentralised/run_ippo_sep_networks.py
  mava/components/jax/building/__init__.py
  mava/components/jax/building/parameter_client.py
  mava/components/jax/training/__init__.py
  mava/components/jax/training/base.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/components/jax/updating/__init__.py
  mava/components/jax/updating/parameter_server.py
  mava/systems/jax/ippo/__init__.py
  mava/systems/jax/ippo/networks.py
  mava/systems/jax/ippo/system.py
  tests/jax/components/building/parameter_client_test.py
  tests/jax/components/training/losses_test.py
  tests/jax/components/training/model_updating_test.py
  tests/jax/components/training/step_test.py
  tests/jax/components/updating/parameter_server_test.py
  tests/jax/integration/parameter_server_test.py
  tests/jax/integration/trainer_test.py
  tests/jax/systems/systems_test_data.py
Labels: refactor, Maintenance, size/XXL

#736 Feature/remove config classes
  docs/create_component.md
  docs/gotchas.md
  examples/jax/quickstart.ipynb
  mava/components/jax/building/adders.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/datasets.py
  mava/components/jax/building/distributor.py
  mava/components/jax/building/environments.py
  mava/components/jax/building/guardrails.py
  mava/components/jax/building/loggers.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/parameter_client.py
  mava/components/jax/building/reverb_components.py
  mava/components/jax/building/system_init.py
  mava/components/jax/component.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/executing/base.py
  mava/components/jax/executing/observing.py
  mava/components/jax/training/advantage_estimation.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/components/jax/updating/parameter_server.py
  mava/components/jax/updating/terminators.py
  mava/systems/jax/config.py
  mava/systems/jax/ippo/components.py
  mava/systems/jax/system.py
  tests/jax/components/building/adders_test.py
  tests/jax/components/executing/base_test.py
  tests/jax/core_system_components/config_test.py
  tests/jax/core_system_components/system_component_test.py
  tests/jax/mocks.py
Labels: enhancement, Maintenance, size/XL

#710 feat: Checkpointer Component
  docs/components/build_components.md
  docs/components/updating_components.md
  examples/README.md
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_restore_checkpoint.py
  examples/jax/quickstart.ipynb
  mava/components/jax/building/__init__.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/distributor.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/optimisers.py
  mava/components/jax/building/parameter_client.py
  mava/components/jax/building/system_init.py
  mava/components/jax/component.py
  mava/components/jax/executing/base.py
  mava/components/jax/training/advantage_estimation.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/components/jax/updating/__init__.py
  mava/components/jax/updating/checkpointer.py
  mava/components/jax/updating/checkpointers.py
  mava/components/jax/updating/parameter_server.py
  mava/constants.py
  mava/systems/jax/ippo/networks.py
  mava/systems/jax/ippo/system.py
  mava/systems/jax/parameter_client.py
  mava/systems/tf/savers.py
  mava/wrappers/__init__.py
  mava/wrappers/saveable.py
  setup.py
  tests/jax/components/building/optimisers_test.py
  tests/jax/components/building/parameter_client_test.py
  tests/jax/components/training/losses_test.py
  tests/jax/components/training/model_updating_test.py
  tests/jax/components/training/step_test.py
  tests/jax/components/training/trainer_test.py
  tests/jax/components/updating/checkpointer_test.py
  tests/jax/components/updating/parameter_server_test.py
  tests/jax/core_system_components/config_test.py
  tests/jax/core_system_components/system_component_test.py
  tests/jax/integration/parameter_server_test.py
  tests/jax/integration/trainer_test.py
  tests/jax/systems/systems_test_data.py
Labels: size/XXL

#751 Bugfix: Convert actions to python integers before stepping MPE environment
  examples/jax/petting_zoo/mpe/simple_reference/feedforward/decentralised/run_ippo.py
  examples/jax/petting_zoo/mpe/simple_speaker_listener/feedforward/decentralised/run_ippo.py
  examples/jax/petting_zoo/mpe/simple_spread/feedforward/decentralised/run_ippo.py
  mava/utils/environments/pettingzoo_utils.py
  mava/wrappers/pettingzoo.py
Labels: bug, size/L

#753 docs: Instructions to make MAVA editable
  docs/gotchas.md
Labels: documentation, size/XS

#756 Maintain: Remove redundant networks dict
  mava/components/jax/building/parameter_client.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/components/jax/updating/parameter_server.py
  mava/systems/jax/ippo/networks.py
  tests/jax/components/building/parameter_client_test.py
  tests/jax/components/executing/action_selection_test.py
  tests/jax/components/training/losses_test.py
  tests/jax/components/training/model_updating_test.py
  tests/jax/components/training/step_test.py
  tests/jax/components/training/trainer_test.py
  tests/jax/components/updating/parameter_server_test.py
  tests/jax/core_system_components/parameter_client_test.py
  tests/jax/integration/parameter_server_test.py
  tests/jax/integration/trainer_test.py
Labels: Maintenance, size/XL

#755 Maintain: Update docs for checkpointer
  docs/components/updating_components.md
  docs/getting_started/create_system.md
  examples/README.md
Labels: documentation, size/S

#767 Fix: Single process launcher
  mava/systems/jax/launcher.py
Labels: bug, size/XS

#768 fix: fix the failing checks
  setup.py
Labels: bug, size/XS

#771 fix: pin the version of jaxlib (checks are failing)
  setup.py
Labels: bug, benchmark, size/XS
