Repository instadeepai/Mava, pull requests merged in 2022-02, with the labels that each got.

#368 Feature/maintainace issue template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/maintainance.md
  CONTRIBUTING.md
Labels: enhancement

#375 feat: filter docker image push based on label.
  .github/workflows/push_docker.yaml
Labels: benchmark

#378 Maintenance/update readme
  README.md
Labels: documentation, size/M

#390 chore: expand code owner list for better code review
  .github/CODEOWNERS
Labels: Maintenance, size/XS

#379 Feature/internal feature issue template
  .github/ISSUE_TEMPLATE/feature_internal.md
Labels: enhancement, size/M

#381 Feature/internal bug issue template
  .github/ISSUE_TEMPLATE/bugfix_internal.md
Labels: enhancement, size/M

#385 feat: benchmarking issue template
  .github/ISSUE_TEMPLATE/benchmarking_internal.md
Labels: enhancement, size/S

#395 Bugfix: Fixed conventional commit pre-commit hook not running.
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: size/XS

#388 Fix/checklist for issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/maintainance.md
Labels: bug, Maintenance, size/M

#399 feat: internal issue tempalte for tests
  .github/ISSUE_TEMPLATE/feature_internal.md
  .github/ISSUE_TEMPLATE/test_internal.md
Labels: enhancement, size/M

#413 Fix/Smac Wrapper Relies on Flatland Installation
  mava/wrappers/__init__.py
Labels: size/XS

#417 fix: readd quickstart notebook
  examples/tf/quickstart.ipynb
Labels: bug, size/XXL

#421 fix: Fix broken tests due to new gym version.
  setup.py
  tests/wrappers/wrapper_test.py
Labels: size/XS

#423 Maintenance: Remove redundant value_network code
  mava/systems/tf/madqn/networks.py
  mava/systems/tf/value_decomposition/networks.py
Labels: Maintenance, size/XS

#432 fix: small bug in the pettingzoo wrapper related to legal action masking
  mava/systems/tf/madqn/execution.py
  mava/wrappers/pettingzoo.py
Labels: bug, size/M

#437 Fix/Flatland Docker Container
  setup.py
Labels: benchmark, size/XS

#405 Feature/jax abstract system class
  mava/core_jax.py
  mava/core_jax_test.py
Labels: enhancement, size/L

#435 Fix/ Fix docs build.
  docs/environments.md
  docs/environments/smac.md
  docs/systems.md
  docs/systems/tf/dial.md
  docs/systems/tf/qmix.md
  docs/systems/tf/value_decomposition.md
  docs/systems/tf/vdn.md
  mava/utils/environments/flatland_utils.py
  mava/wrappers/flatland.py
  mkdocs.yml
  tests/utils/environment_utils_test.py
  tests/wrappers/wrapper_test.py
Labels: size/M

#414 Feature/jax mava custom config class
  mava/systems/jax/__init__.py
  mava/systems/jax/config.py
  mava/systems/jax/config_test.py
  mava/utils/config_utils.py
  tests/utils/config_utils_test.py
Labels: enhancement, size/XL

#438 Feat/Release new mava version.
  mava/_metadata.py
Labels: size/XS

#441 Fix/add loss mask to ppo
  .github/ISSUE_TEMPLATE/bugfix_internal.md
  mava/systems/tf/mappo/training.py
Labels: size/S
