Repository instadeepai/Mava, pull requests merged in 2022-12, with the labels that each got.

#853 feat: added `core_component.has` method
  mava/core_jax.py
  tests/core_system_components/core_jax_test.py
Labels: size/L

#844 Fix: failing checks fix
  tests/systems/ippo_system_evaluation_test.py
  tests/systems/systems_test_data.py
Labels: bug, size/S

#852 feat: observation and value norm components
  mava/components/executing/action_selection.py
  mava/components/normalisation/__init__.py
  mava/components/normalisation/base_normalisation.py
  mava/components/normalisation/observation_normalisation.py
  mava/components/normalisation/value_normalisation.py
  mava/components/training/model_updating.py
  mava/components/training/step.py
  mava/components/training/trainer.py
  mava/components/updating/parameter_server.py
  mava/systems/ippo/system.py
  mava/utils/jax_training_utils.py
  tests/components/building/adders_test.py
  tests/components/building/networks_test.py
  tests/components/executing/action_selection_test.py
  tests/components/training/observation_normalisation_test.py
  tests/components/training/step_test.py
  tests/components/training/value_normalisation_test.py
  tests/mocks.py
  tests/systems/systems_test_data.py
Labels: size/XL, benchmark complete

#854 Feature/best checkpoint component
  examples/smac/feedforward/decentralised/best_checkpointed_net.py
  mava/components/building/__init__.py
  mava/components/building/best_checkpointer.py
  mava/components/building/parameter_client.py
  mava/components/updating/checkpointer.py
  mava/components/updating/parameter_server.py
  mava/environment_loop.py
  mava/systems/ippo/system.py
  tests/components/building/best_checkpointer_test.py
Labels: priority/medium, size/L

#846 Bugfix: Data shuffling
  docs/getting_started/create_system.md
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_eval_intervals.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_grid_search.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_huber.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_json_logger.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_layer_norm.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_othogonal_network_init.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_restore_checkpoint.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_monitoring.py
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_value_norm.py
  examples/debugging/simple_spread/recurrent/decentralised/run_ippo.py
  examples/flatland/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/mpe/simple_reference/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/mpe/simple_speaker_listener/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/mpe/simple_spread/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/simple_spread/feedforward/decentralised/run_ippo.py
  examples/quickstart.ipynb
  examples/smac/feedforward/decentralised/best_checkpointed_net.py
  examples/smac/feedforward/decentralised/run_ippo.py
  examples/smac/feedforward/decentralised/run_ippo_eval_intervals.py
  examples/smac/feedforward/decentralised/run_ippo_json_logger.py
  examples/smac/feedforward/decentralised/run_ippo_sep_networks.py
  examples/smac/feedforward/decentralised/run_ippo_smac_death_masking.py
  mava/components/building/datasets.py
  mava/components/training/losses.py
  mava/components/training/model_updating.py
  mava/components/training/step.py
  mava/systems/ippo/config.py
  mava/systems/launcher.py
  tests/components/building/datasets_test.py
  tests/components/training/losses_test.py
  tests/components/training/model_updating_test.py
  tests/components/training/step_test.py
  tests/systems/systems_test_data.py
Labels: bug, size/L, benchmark complete

#793 Feature: Observations stacking
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_frame_stacking.py
  examples/smac/feedforward/decentralised/run_ippo_smac_frame_stacking.py
  mava/utils/environments/debugging_utils.py
  mava/utils/environments/flatland_utils.py
  mava/utils/environments/pettingzoo_utils.py
  mava/utils/environments/smac_utils.py
  mava/wrappers/env_preprocess_wrappers.py
  tests/wrappers/wrapper_test.py
Labels: enhancement, size/XL, benchmark complete

#841 Feature: absolute metric
  examples/smac/feedforward/decentralised/calculate_absolute_metric.py
  mava/components/building/best_checkpointer.py
  mava/components/updating/checkpointer.py
  mava/components/updating/parameter_server.py
  mava/components/updating/terminators.py
  mava/environment_loop.py
  mava/systems/trainer.py
  mava/utils/checkpointing_utils.py
  tests/components/building/best_checkpointer_test.py
  tests/components/updating/parameter_server_test.py
  tests/components/updating/terminators_test.py
  tests/core_system_components/trainer_test.py
  tests/integration/parameter_server_test.py
  tests/systems/systems_test_data.py
  tests/test_utils/checkpointing_utils_test.py
Labels: enhancement, size/XL
