Repository instadeepai/Mava, pull requests merged in 2022-06, with the labels that each got.

#505 feat: add PPO action masking for the discrete setting
  examples/tf/flatland/__init__.py
  mava/components/jax/executing/action_selection.py
  mava/systems/jax/mappo/networks.py
  mava/utils/jax_training_utils.py
Labels: size/M

#514 fix: mypy fix for chex imports
  mypy.ini
Labels: size/XS

#497 feature: added useful utils for working with stacked pytrees
  mava/utils/jax_tree_utils.py
Labels: size/S

#512 Feature/jax systems termination condition
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_mappo.py
  mava/components/jax/updating/__init__.py
  mava/components/jax/updating/terminators.py
  mava/systems/jax/mappo/system.py
  mava/utils/training_utils.py
Labels: size/L

#511 Feature/component abstract classes
  mava/components/jax/building/datasets.py
  mava/components/jax/building/networks.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/executing/observing.py
  mava/components/jax/training/__init__.py
  mava/components/jax/training/step.py
  mava/components/jax/updating/parameter_server.py
  mava/systems/jax/mappo/system.py
Labels: size/L

#517 chore: update code owners
  .github/CODEOWNERS
Labels: Maintenance, size/S

#556 Feature/termination condition component change
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_mappo.py
  mava/components/jax/updating/terminators.py
Labels: size/S

#559 Feature/jax systems termination condition unit tests
  mypy.ini
  tests/jax/updating/terminators_test.py
  tests/jax/updating/terminators_test_data.py
Labels: size/L

#502 feature: add optional observation network to ppo default networks
  examples/jax/petting_zoo/__init__.py
  examples/jax/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_mappo.py
  mava/systems/jax/mappo/networks.py
Labels: enhancement, size/L

#563 fix: remove redundant storing of shared weights config in store
  mava/components/jax/building/networks.py
Labels: size/XS

#551 test: unit tests for jax logging components
  tests/jax/components/building/loggers_test.py
  tests/jax/mocks.py
Labels: size/L

#571 Feature/jax test coverage reporting
  .coveragerc
Labels: size/XS

#570 Bugfix/pre commit exclude mava/lib
  pyproject.toml
Labels: size/XS

#566 Tests/jax components/action selection
  tests/jax/components/executing/action_selection_test.py
Labels: size/L

#560 feature: extra info in config common parameter names exception
  mava/systems/jax/config.py
Labels: size/S

#552 Bugfix/fix old tf architectures
  Dockerfile
  README.md
  bash_scripts/install_meltingpot.sh
  bash_scripts/tests.sh
  docs/requirements.txt
  mava/components/tf/architectures/centralised.py
  mava/components/tf/architectures/networked.py
  mava/components/tf/architectures/state_based.py
  mava/systems/tf/maddpg/training.py
  mava/systems/tf/mappo/training.py
  mava/utils/debugging/environment.py
  mava/utils/debugging/environments/two_step.py
  mava/utils/environments/RoboCup_env/robocup_utils/util_functions.py
  mava/wrappers/debugging_envs.py
  setup.py
  tests/systems/mad4pg_system_test.py
  tests/systems/maddpg_system_test.py
  tests/systems/mappo_system_test.py
  tests/systems/qmix_system_test.py
  tests/systems/vdn_system_test.py
Labels: benchmark, size/L

#588 fix: move terminators test to correct folder
  tests/jax/components/updating/terminators_test.py
  tests/jax/components/updating/terminators_test_data.py
Labels: size/XS

#580 Tests/jax components/executing/base
  tests/jax/components/executing/base_test.py
Labels: size/L

#585 feat: split SystemInit component into three different components.
  mava/components/jax/building/__init__.py
  mava/components/jax/building/base.py
  mava/components/jax/building/system_init.py
  mava/systems/jax/mappo/system.py
  tests/jax/components/building/adders_test.py
  tests/jax/components/building/data_server_test_data.py
  tests/jax/core_system_components/builder_test.py
  tests/jax/core_system_components/executor_test.py
  tests/jax/core_system_components/parameter_server_test.py
Labels: size/L

#574 Test/core parameter server
  tests/jax/core_system_components/parameter_server_test.py
  tests/jax/hook_order_tracking.py
  tests/jax/mocks.py
  tests/jax/utils.py
Labels: size/L

#557 test: jax network components
  tests/jax/components/building/networks_test.py
Labels: size/L

#593 Test/jax core trainer unit test
  tests/jax/core_system_components/trainer_test.py
Labels: size/M

#594 refactor: rename trainer and param server init config to store
  mava/systems/jax/builder.py
  mava/systems/jax/parameter_server.py
  mava/systems/jax/trainer.py
  tests/jax/components/training/advantage_estimation_test.py
  tests/jax/core_system_components/parameter_server_test.py
Labels: size/S

#584 Fix/fix types jax systems + dev merge
  Dockerfile
  README.md
  bash_scripts/check_format.sh
  bash_scripts/install_meltingpot.sh
  bash_scripts/tf_tests.sh
  docs/requirements.txt
  examples/jax/flatland/__init__.py
  examples/jax/petting_zoo/__init__.py
  examples/jax/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_mappo.py
  examples/jax/smac/__init__.py
  examples/tf/debugging/__init__.py
  examples/tf/openspiel/__init__.py
  examples/tf/petting_zoo/__init__.py
  examples/tf/robocup/__init__.py
  examples/tf/sisl/multiwalker/feedforward/decentralised/run_mappo.py
  examples/tf/smac/__init__.py
  mava/components/tf/architectures/centralised.py
  mava/components/tf/architectures/networked.py
  mava/components/tf/architectures/state_based.py
  mava/systems/tf/maddpg/training.py
  mava/systems/tf/mappo/training.py
  mava/utils/debugging/environment.py
  mava/utils/debugging/environments/two_step.py
  mava/utils/environments/RoboCup_env/robocup_utils/util_functions.py
  mava/wrappers/debugging_envs.py
  mypy.ini
  setup.py
  tests/jax/components/executing/action_selection_test.py
  tests/jax/components/executing/base_test.py
  tests/jax/components/updating/terminators_test.py
  tests/tf/systems/mad4pg_system_test.py
  tests/tf/systems/maddpg_system_test.py
  tests/tf/systems/mappo_system_test.py
  tests/tf/systems/qmix_system_test.py
  tests/tf/systems/vdn_system_test.py
Labels: size/L

#600 Fix/jax cuda install
  Dockerfile
  README.md
Labels: size/S
