Repository instadeepai/Mava, pull requests merged in 2022-08, with the labels that each got.

#653 docs: Documentation for Mava components
  mava/components/jax/building/adders.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/datasets.py
  mava/components/jax/building/distributor.py
  mava/components/jax/building/environments.py
  mava/components/jax/building/loggers.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/parameter_client.py
  mava/components/jax/building/reverb_components.py
  mava/components/jax/building/system_init.py
  mava/components/jax/component.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/executing/base.py
  mava/components/jax/executing/observing.py
  mava/components/jax/training/advantage_estimation.py
  mava/components/jax/training/base.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/components/jax/updating/parameter_server.py
  mava/components/jax/updating/terminators.py
  tests/jax/mocks.py
Labels: size/XL

#657 Docs/core jax
  mava/systems/jax/builder.py
  mava/systems/jax/config.py
  mava/systems/jax/executor.py
  mava/systems/jax/launcher.py
  mava/systems/jax/parameter_client.py
  mava/systems/jax/parameter_server.py
  mava/systems/jax/system.py
  mava/systems/jax/trainer.py
Labels: size/L

#630 Test/jax components/training/step
  tests/jax/components/training/step_test.py
  tests/jax/components/training/step_test_data.py
Labels: size/XL

#596 Feature/dependency guardrails
  .gitignore
  mava/components/jax/building/adders.py
  mava/components/jax/building/data_server.py
  mava/components/jax/building/datasets.py
  mava/components/jax/building/distributor.py
  mava/components/jax/building/environments.py
  mava/components/jax/building/guardrails.py
  mava/components/jax/building/loggers.py
  mava/components/jax/building/networks.py
  mava/components/jax/building/parameter_client.py
  mava/components/jax/building/reverb_components.py
  mava/components/jax/building/system_init.py
  mava/components/jax/component.py
  mava/components/jax/executing/action_selection.py
  mava/components/jax/executing/base.py
  mava/components/jax/executing/observing.py
  mava/components/jax/training/__init__.py
  mava/components/jax/training/advantage_estimation.py
  mava/components/jax/training/base.py
  mava/components/jax/training/losses.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/components/jax/training/trainer.py
  mava/components/jax/updating/parameter_server.py
  mava/components/jax/updating/terminators.py
  mava/systems/jax/mappo/system.py
  mypy.ini
  setup.py
  tests/jax/components/building/adders_test.py
  tests/jax/components/building/data_server_test.py
  tests/jax/components/building/datasets_test.py
  tests/jax/components/executing/base_test.py
  tests/jax/components/training/model_updating_test.py
  tests/jax/components/training/step_test.py
Labels: size/XL

#656 docs: MAPPO network
  mava/systems/jax/mappo/components.py
  mava/systems/jax/mappo/networks.py
  mava/systems/jax/mappo/system.py
Labels: size/L

#684 Fix: Remove redundant bugfix issue template
  .github/ISSUE_TEMPLATE/bugfix_internal.md
Labels: enhancement, size/M

#683 Bugfix/partial dependency imports
  mava/components/jax/training/__init__.py
  mava/components/jax/training/losses.py
  tests/jax/components/training/step_test.py
Labels: size/M

#693 Chore/Rename JAX mappo to ippo
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_sep_networks.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_with_monitoring.py
  examples/jax/flatland/feedforward/decentralised/run_ippo.py
  examples/jax/petting_zoo/butterfly/cooperative_pong/feedforward/decentralised/run_ippo.py
  examples/jax/smac/feedforward/decentralised/run_ippo.py
  examples/jax/smac/feedforward/decentralised/run_ippo_sep_networks.py
  mava/systems/jax/ippo/README.md
  mava/systems/jax/ippo/__init__.py
  mava/systems/jax/ippo/components.py
  mava/systems/jax/ippo/config.py
  mava/systems/jax/ippo/networks.py
  mava/systems/jax/ippo/system.py
  mava/systems/jax/mappo/README.md
  tests/jax/integration/executor_test.py
  tests/jax/integration/parameter_server_test.py
  tests/jax/systems/ippo_system_test.py
Labels: size/L

#692 Chore/numpy jax minor updates
  mava/adders/reverb/transition.py
  mava/components/jax/training/model_updating.py
  mava/components/jax/training/step.py
  mava/utils/debugging/rendering.py
  mava/utils/jax_tree_utils.py
  mava/utils/wrapper_utils.py
  mava/wrappers/open_spiel.py
  setup.py
  tests/jax/components/training/model_updating_test.py
  tests/jax/components/training/step_test.py
  tests/tf/wrappers/wrapper_test.py
Labels: size/M

#689 Feature: Markdown file explaining how new Mava works
  OPTIONAL_INSTALL.md
  README.md
  docs/add_doc.md
  docs/annotation.md
  docs/components/build_components.md
  docs/components/components.md
  docs/components/core_components.md
  docs/components/executing_components.md
  docs/components/train_components.md
  docs/components/updating_components.md
  docs/config.md
  docs/create_component.md
  docs/create_system.md
  docs/gotchas.md
  docs/images/jax_logo_small.png
  docs/index.md
  docs/overview.md
  docs/requirements.txt
  docs/store.md
  docs/systems/jax/ippo.md
  docs/systems/tf/mad4pg.md
  docs/systems/tf/maddpg.md
  docs/systems/tf/madqn.md
  docs/systems/tf/mappo.md
  docs/systems/tf/value_decomposition.md
  examples/README.md
  mava/systems/README.md
  mkdocs.yml
Labels: documentation, size/XXL

#654 feat: full ippo system integration test
  mava/systems/jax/launcher.py
  tests/jax/components/building/distributor_test.py
  tests/jax/core_system_components/launcher_test.py
  tests/jax/systems/ippo_system_test.py
Labels: test, size/L

#695 Fix: Docs not updating
  mava/systems/README.md
Labels: size/XS

#675 Test: trainer integration test and system integration test editing
  tests/jax/integration/mock_systems.py
  tests/jax/integration/trainer_test.py
  tests/jax/systems/ippo_system_test.py
Labels: test, size/L

#699 Feature: Remove multi-threading
  examples/jax/debugging/simple_spread/feedforward/decentralised/run_ippo_single_process.py
  mava/components/jax/building/distributor.py
  mava/systems/jax/launcher.py
  tests/jax/integration/mock_systems.py
  tests/jax/integration/trainer_test.py
Labels: enhancement, size/L

#674 Test: integration test of the Data Server
  tests/jax/integration/data_server_test.py
  tests/jax/integration/data_server_test_data.py
Labels: test, size/L

#700 fix: fix the ippo test and add a test flag
  mava/components/jax/building/distributor.py
  mava/systems/jax/launcher.py
  mava/systems/tf/madqn/builder.py.isorted
  tests/jax/systems/ippo_system_test.py
Labels: enhancement, test, size/S

#680 test: parameter server integration test
  tests/jax/integration/parameter_server_test.py
Labels: test, size/L

#703 Feat: Launchpad integration test
  mava/components/jax/building/distributor.py
  mava/systems/jax/launcher.py
  mava/wrappers/environment_loop_wrappers.py
  tests/jax/integration/data_server_test.py
  tests/jax/integration/evaluator_test.py
  tests/jax/integration/executor_test.py
  tests/jax/integration/multi_thread_test.py
  tests/jax/integration/parameter_server_test.py
  tests/jax/integration/trainer_test.py
  tests/jax/systems/ippo_system_test.py
  tests/jax/systems/systems_test_data.py
Labels: size/L
