Repository instadeepai/Mava, pull requests merged in 2022-01, with the labels that each got.

#344 Bugfix/dockerfile no module found
  .github/workflows/push_docker.yaml
  Dockerfile
  Makefile
  README.md
Labels: bug

#348 Mava Redesign/Update Launcher
  mava/components/building/__init__.py
  mava/components/building/setup.py
  mava/systems/building.py
  mava/systems/launcher.py
  mava/systems/tf/maddpg_v2/building.py
Labels: enhancement

#349 Minor bug-fixing to get redesign Launcher running.
  mava/__init__.py
  mava/core.py
  mava/environment_loop.py
  mava/environment_loops/open_spiel_environment_loop.py
  mava/systems/launcher.py
  mava/wrappers/environment_loop_wrappers.py
  tests/system.py
Labels: bug

#352 Feature/bugfix redesign callbacks
  mava/callbacks/__init__.py
  mava/callbacks/base.py
  mava/callbacks/callback_hook.py
  mava/components/building/__init__.py
  mava/components/building/distributor.py
  mava/components/building/setup.py
  mava/systems/building.py
  mava/systems/system.py
  mava/systems/tf/maddpg/system.py
  mava/systems/tf/maddpg_v2/system.py
  mava/systems/tf/madqn/system.py
  mava/systems/tf/mappo/system.py
  mava/systems/tf/qmix/system.py
  mava/systems/tf/vdn/system.py
  mava/systems/training.py
  tests/system.py
Labels: bug, enhancement

#354 Feature/auto docs
  .readthedocs.yaml
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  docs/CONTRIBUTING.md
  docs/OPTIONAL_INSTALL.md
  docs/TROUBLESHOOTING.md
  docs/add_doc.md
  docs/environments.md
  docs/environments/debugging.md
  docs/environments/flatland.md
  docs/environments/general.md
  docs/environments/meltingpot.md
  docs/environments/open_spiel.md
  docs/environments/pettingzoo.md
  docs/environments/robocup.md
  docs/environments/smac.md
  docs/examples.md
  docs/index.md
  docs/requirements.txt
  docs/systems.md
  docs/systems/general.md
  docs/systems/tf/dial.md
  docs/systems/tf/mad4pg.md
  docs/systems/tf/maddpg.md
  docs/systems/tf/madqn.md
  docs/systems/tf/mappo.md
  docs/systems/tf/qmix.md
  docs/systems/tf/vdn.md
  examples/README.md
  mava/systems/README.md
  mava/systems/tf/dial/README.md
  mava/systems/tf/mad4pg/README.md
  mava/systems/tf/maddpg/README.md
  mava/systems/tf/madqn/README.md
  mava/systems/tf/mappo/README.md
  mava/systems/tf/qmix/README.md
  mava/systems/tf/vdn/README.md
  mkdocs.yml
  pyproject.toml
Labels: enhancement
