Repository instadeepai/Mava, pull requests merged in 2022-11, with the labels that each got.

#803 [chore] instruction for installing mava for developement
  CONTRIBUTING.md
  DETAILED_INSTALL.md
Labels: documentation, size/S, priority/low

#817 fix: Agent id observation mismatch
  DETAILED_INSTALL.md
  mava/adders/reverb/base.py
  mava/components/updating/terminators.py
  mava/environment_loop.py
  mava/systems/trainer.py
Labels: bug, size/S, benchmark complete

#775 Feature/json logger
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_json_logger.py
  examples/petting_zoo/mpe/simple_reference/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/mpe/simple_speaker_listener/feedforward/decentralised/run_ippo.py
  examples/petting_zoo/mpe/simple_spread/feedforward/decentralised/run_ippo.py
  examples/smac/feedforward/decentralised/run_ippo_json_logger.py
  mava/components/building/environments.py
  mava/components/building/loggers.py
  mava/components/building/system_init.py
  mava/components/updating/parameter_server.py
  mava/environment_loop.py
  mava/systems/ippo/config.py
  mava/utils/environments/debugging_utils.py
  mava/utils/environments/flatland_utils.py
  mava/utils/environments/pettingzoo_utils.py
  mava/utils/environments/robocup_utils.py
  mava/utils/environments/smac_utils.py
  mava/utils/loggers/base.py
  mava/utils/loggers/eval_json_logger.py
  tests/components/building/environments_test.py
  tests/components/building/loggers_test.py
  tests/integration/evaluator_test.py
  tests/integration/executor_test.py
  tests/integration/networks_test.py
  tests/mocks.py
  tests/test_utils/environment_utils_test.py
  tests/test_utils/eval_json_logger_test.py
Labels: enhancement, size/XXL

#804 Feature/death masking normalisation
  examples/debugging/simple_spread/feedforward/decentralised/run_ippo_with_value_norm.py
  mava/components/building/environments.py
  mava/components/executing/action_selection.py
  mava/components/training/model_updating.py
  mava/components/training/step.py
  mava/components/training/trainer.py
  mava/systems/executor.py
  mava/utils/environments/debugging_utils.py
  mava/utils/jax_training_utils.py
  mava/wrappers/env_preprocess_wrappers.py
  mava/wrappers/env_wrappers.py
  mava/wrappers/pettingzoo.py
  mava/wrappers/smac.py
  tests/components/executing/action_selection_test.py
  tests/components/training/normalisation_test.py
  tests/components/training/step_test.py
  tests/components/training/trainer_test.py
  tests/mocks.py
  tests/wrappers/wrapper_test.py
Labels: size/XL, benchmark complete

#830 fix: bug optional MLP layer after recurrent layer is never called
  mava/systems/ippo/networks.py
Labels: size/S

#825 feature: made a general extras spec component
  mava/components/building/__init__.py
  mava/components/building/extras_spec.py
  mava/systems/ippo/components.py
  tests/components/building/extras_spec_test.py
Labels: refactor, priority/low, size/L

#814 Feature: best checkpointer
  examples/smac/feedforward/decentralised/best_checkpointed_net.py
  examples/smac/feedforward/decentralised/run_ippo.py
  examples/smac/feedforward/decentralised/run_ippo_eval_intervals.py
  examples/smac/feedforward/decentralised/run_ippo_sep_networks.py
  mava/components/building/parameter_client.py
  mava/components/executing/observing.py
  mava/components/updating/checkpointer.py
  mava/components/updating/parameter_server.py
  mava/core_jax.py
  mava/environment_loop.py
  mava/systems/parameter_client.py
  mava/utils/checkpointing_utils.py
  tests/components/building/parameter_client_test.py
  tests/components/executing/observing_test.py
  tests/components/updating/checkpointer_test.py
  tests/components/updating/parameter_server_test.py
  tests/systems/systems_test_data.py
  tests/test_utils/checkpointing_utils_test.py
Labels: enhancement, priority/high, size/XL

#836 fix: pin jax cuda version in dockerfile to match version in setup file.
  Dockerfile
Labels: bug, size/XS

#847 fix: parameter client segmentation fault
  mava/components/building/parameter_client.py
  mava/systems/parameter_client.py
  mava/utils/done_future.py
  tests/components/building/parameter_client_test.py
  tests/core_system_components/parameter_client_test.py
  tests/test_utils/done_future_test.py
Labels: size/L

#855 chore: Update codecov settings.
  .github/codecov.yml
Labels: size/S
