Repository instadeepai/Mava, pull requests merged in 2023-11, with the labels that each got.

#944 chore: unpin jax version
  requirements/requirements.txt
Labels: size/XS

#940 feat: type callables
  mava/evaluator.py
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/types.py
Labels: size/L

#942 feat: logging steps per second
  examples/Quickstart.ipynb
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/utils/timing_utils.py
Labels: size/L

#947 Maintenance/remove sacred
  mava/configs/logger/base_logger.yaml
  mava/configs/logger/ff_ippo.yaml
  mava/configs/logger/ff_mappo.yaml
  mava/configs/logger/rec_ippo.yaml
  mava/configs/logger/rec_mappo.yaml
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/utils/logger_tools.py
  requirements/requirements.txt
Labels: maintenance, size/L

#950 Feat/add marl eval json logger
  mava/configs/logger/base_logger.yaml
  mava/configs/logger/ff_ippo.yaml
  mava/configs/logger/ff_mappo.yaml
  mava/configs/logger/rec_ippo.yaml
  mava/configs/logger/rec_mappo.yaml
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/utils/logger_tools.py
Labels: size/L

#954 feat: Model Checkpointing
  .gitignore
  mava/configs/logger/base_logger.yaml
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/utils/checkpointing.py
  pyproject.toml
Labels: size/L
