Repository instadeepai/Mava, pull requests merged in 2023-01, with the labels that each got.

#865 fix: import of required packages in quickstart to run on Colab.
  examples/quickstart.ipynb
  setup.py
Labels: size/M

#861 feat: make best checkpoint support norm params
  examples/smac/feedforward/decentralised/best_checkpointed_net.py
  examples/smac/feedforward/decentralised/best_checkpointed_net/create_network_checkpoint.py
  examples/smac/feedforward/decentralised/best_checkpointed_net/run_checkpointed_net.py
  mava/components/building/best_checkpointer.py
  mava/components/updating/checkpointer.py
  mava/environment_loop.py
  mava/utils/checkpointing_utils.py
  tests/components/building/best_checkpointer_test.py
  tests/test_utils/checkpointing_utils_test.py
Labels: enhancement, size/L

#875 Fix: fixing the recording of agents in the quickstart example
  examples/quickstart.ipynb
Labels: bug, size/M

#888 feat: Add s3 support to tensorboard logging.
  mava/utils/loggers/base.py
  mypy.ini
  tests/components/building/loggers_test.py
  tests/wrappers/wrapper_test.py
Labels: enhancement, size/M

#886 Feature/single file structure
  .github/codecov.yml
  .github/workflows/push_docker.yaml
  .gitignore
  Dockerfile
  educational/Dockerfile
  educational/Makefile
  educational/README.md
  educational/bash_scripts/random_agent_8m.sh
  educational/common/environment_loops.py
  educational/common/replay_buffer.py
  educational/requirements.txt
  educational/systems/policy_optimization/ddpg/README.md
  educational/systems/policy_optimization/ddpg/ddpg.py
  educational/systems/policy_optimization/ddpg/maddpg.py
  educational/systems/policy_optimization/ppo/README.md
  educational/systems/policy_optimization/ppo/ippo.py
  educational/systems/policy_optimization/ppo/mappo.py
  educational/systems/random_agent.py
  educational/systems/template.py
  educational/systems/value_based/README.md
  educational/systems/value_based/idqn.py
  educational/systems/value_based/qmix.py
  educational/systems/value_based/rdqn.py
  educational/systems/value_based/vdn.py
  mava/utils/environments/smac_utils.py
  mava/wrappers/debugging_envs.py
  setup.py
Labels: size/XL, educational benchmark required

#890 bugfix: observation stacking wrapper test
  tests/wrappers/wrapper_test.py
Labels: size/XS

#892 Feature/Bugfix: Simplified adders and policy state fix
  .coveragerc
  bash_scripts/check_format.sh
  bash_scripts/local_tests.sh
  bash_scripts/local_tests_venv.sh
  bash_scripts/tests.sh
  mava/adders/base.py
  mava/adders/reverb/base.py
  mava/adders/reverb/episode.py
  mava/adders/reverb/sequence.py
  mava/adders/reverb/transition.py
  mava/components/building/adders.py
  mava/components/executing/observing.py
  mava/systems/ippo/config.py
  mava/types.py
  tests/adders/adders_utils.py
  tests/adders/episode_adders_test_data.py
  tests/adders/sequence_adders_test_data.py
  tests/adders/transition_adders_test_data.py
  tests/components/building/adders_test.py
  tests/components/executing/observing_test.py
  tests/systems/systems_test_data.py
Labels: bug, maintenance, size/L, benchmark required
