Repository instadeepai/Mava, pull requests merged in 2023-12, with the labels that each got.

#956 feat: change jumanji path
  examples/Quickstart.ipynb
  requirements/requirements.txt
Labels: size/L

#957 feat: upgrade recurrent networks to new flax api
  mava/configs/logger/base_logger.yaml
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  requirements/requirements.txt
Labels: enhancement, maintenance, size/S, benchmark complete

#960 docs: update see also
  README.md
Labels: size/S

#958 feat: make file utils
  mava/configs/default_ff_ippo_lbf.yaml
  mava/configs/env/scenario/15x15-3p-5f.yaml
  mava/configs/system/ff_ippo.yaml
  mava/configs/system/ff_mappo.yaml
  mava/configs/system/rec_ippo.yaml
  mava/configs/system/rec_mappo.yaml
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/systems/rec_mappo_rware.py
  mava/utils/make_env.py
Labels: size/XL

#955 feat: jaxmarl wrapper
  mava/configs/env/smax.yaml
  mava/types.py
  mava/utils/make_env.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/shared.py
  requirements/requirements.txt
Labels: size/L

#963 feat: update readme with simple instructions for running systems
  README.md
  mava/configs/arch/anakin.yaml
Labels: documentation, maintenance, size/S

#966 Update codeowners
  .github/CODEOWNERS
Labels: size/XS

#962 Feat/add time to json logger
  mava/utils/logger_tools.py
Labels: enhancement, size/S

#964 feat: Vault PoC
  .gitignore
  README.md
  mava/advanced_usage/README.md
  mava/advanced_usage/ff_ippo_store_experience.py
  requirements/requirements.txt
Labels: size/XL

#967 docs: add TRC ack
  README.md
Labels: size/XS

#969 Docs/update readme
  README.md
Labels: size/S

#971 Docs/update readme
  README.md
Labels: size/S
