Repository instadeepai/Mava, pull requests merged in 2023-09, with the labels that each got.

#928 feat: Split Net in the Quickstart notebook
  Quickstart.ipynb
Labels: maintenance, size/L

#935 chore: flake8 maintenance
  .pre-commit-config.yaml
  pyproject.toml
  requirements/requirements-dev.txt
  setup.cfg
Labels: size/M

#937 docs: refactor
  .pre-commit-config.yaml
  README.md
  TROUBLESHOOTING.md
  docs/CONTRIBUTING.md
  docs/DETAILED_INSTALL.md
  docs/license_header.txt
  examples/Quickstart.ipynb
Labels: documentation, size/S

#934 feat: update neptune
  mava/configs/default.yaml
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/utils/logger_tools.py
  requirements/requirements.txt
Labels: maintenance, size/L
