Repository instadeepai/Mava, pull requests merged in 2023-08, with the labels that each got.

#905 feat: Feedforward IPPO JAX Agent implemented
  Makefile
  jax_distribution/README.md
  jax_distribution/systems/ff_ippo_rware.py
  jax_distribution/systems/ippo_vmap_only.py
  jax_distribution/types.py
  jax_distribution/utils/jax.py
  jax_distribution/utils/timing_utils.py
  jax_distribution/wrappers/jumanji.py
  jax_distribution/wrappers/purejaxrl.py
Labels: enhancement, size/XXL

#909 Feat: recurrent ippo vmapped agents
  jax_distribution/evaluator.py
  jax_distribution/systems/rec_ippo_rware.py
  jax_distribution/types.py
Labels: enhancement, size/XL

#913 Maintenance/add task names to configs
  jax_distribution/configs/default.yaml
  jax_distribution/configs/rware_scenario/small-4ag.yaml
  jax_distribution/configs/rware_scenario/tiny-2ag.yaml
  jax_distribution/configs/rware_scenario/tiny-4ag-easy.yaml
  jax_distribution/configs/rware_scenario/tiny-4ag.yaml
  jax_distribution/systems/ff_ippo_rware.py
  jax_distribution/systems/ff_mappo_rware.py
  jax_distribution/systems/rec_ippo_rware.py
  jax_distribution/systems/rec_mappo_rware.py
  jax_distribution/utils/logger_tools.py
Labels: size/L

#914 Maintenance/move folder structure
  .gitignore
  jax_distribution/README.md
  jax_distribution/requirements.txt
  mava/configs/default.yaml
  mava/configs/rware_scenario/small-4ag.yaml
  mava/configs/rware_scenario/tiny-2ag.yaml
  mava/configs/rware_scenario/tiny-4ag-easy.yaml
  mava/configs/rware_scenario/tiny-4ag.yaml
  mava/evaluator.py
  mava/logger.py
  mava/systems/__init__.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/types.py
  mava/utils/__init__.py
  mava/utils/jax.py
  mava/utils/logger_tools.py
  mava/utils/timing_utils.py
  mava/wrappers/__init__.py
  mava/wrappers/jumanji.py
  pyproject.toml
  requirements/requirements.txt
  tests/.gitkeep
Labels: size/L

#915 feat: changed logging path
  mava/configs/default.yaml
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/utils/logger_tools.py
Labels: size/M

#917 Feat/jax mava dockerfile
  .dockerignore
  CONTRIBUTING.md
  DETAILED_INSTALL.md
  Dockerfile
  Makefile
  TROUBLESHOOTING.md
  requirements/requirements.txt
Labels: size/L

#919 Docs: Updating the Quickstart Notebook
  Quickstart.ipynb
Labels: enhancement, size/XL

#920 Feat: split actor-critic networks
  .gitignore
  mava/configs/default.yaml
  mava/evaluator.py
  mava/logger.py
  mava/systems/ff_ippo_rware.py
  mava/systems/ff_mappo_rware.py
  mava/systems/rec_ippo_rware.py
  mava/systems/rec_mappo_rware.py
  mava/types.py
  mava/utils/logger_tools.py
  mava/wrappers/jumanji.py
  requirements/requirements.txt
Labels: enhancement, size/XXL

#924 Feat/pre release cleanup
  .github/workflows/release.yaml
  Quickstart.ipynb
  README.md
Labels: size/L

#925 fix: fix experiment parameters not being set in neptune
  mava/utils/logger_tools.py
Labels: size/XS

#926 feat: log environment timestep to x-axis on neptune
  mava/utils/logger_tools.py
Labels: enhancement, size/M

#927 Fix: fixing global-obs shape in case of no agent-id
  mava/wrappers/jumanji.py
Labels: bug, size/S
