Repository instadeepai/Mava, pull requests merged in 2024-02, with the labels that each got.

#997 Feat/store json to neptune
  mava/configs/logger/base_logger.yaml
  mava/utils/logger.py
Labels: enhancement, size/M

#994 feat: stop accessing LogEnvState variables directly
  examples/Quickstart.ipynb
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/types.py
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/episode_metrics.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/observation.py
Labels: size/L

#1004 fix: use correct fbx location
  requirements/requirements.txt
Labels: size/XS

#1003 fix: use correct rware timelimit
  mava/configs/env/rware.yaml
Labels: size/XS

#1005 feat: use pypi's version for fbx
  requirements/requirements.txt
Labels: size/XS

#1008 fix: use new Vault API for example
  mava/advanced_usage/README.md
Labels: size/S

#1011 Maintenance/update readme
  README.md
  docs/images/lbf_results/15x15-4p-3f_rec_mappo.png
  docs/images/lbf_results/2s-8x8-2p-2f-coop_rec_mappo.png
  docs/images/lbf_results/legend_rec_mappo.png
  docs/images/rware_results/ff_mappo/main_readme/legend.png
  docs/images/rware_results/ff_mappo/main_readme/small-4ag-1.png
  docs/images/rware_results/ff_mappo/main_readme/tiny-2ag-1.png
  docs/images/rware_results/ff_mappo/main_readme/tiny-4ag-1.png
  docs/images/smax_results/10m_vs_11m.png
  docs/images/smax_results/27m_vs_30m.png
  docs/images/smax_results/2s3z.png
  docs/images/smax_results/3s5z.png
  docs/images/smax_results/3s5z_vs_3s6z.png
  docs/images/smax_results/3s_vs_5z.png
  docs/images/smax_results/5m_vs_6m.png
  docs/images/smax_results/6h_vs_8z.png
  docs/images/smax_results/legend.png
  docs/smax_benchmark.md
Labels: documentation, size/L

#1010 fix: cast timestep to int
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
Labels: size/S

#1014 fix: fix PureJax link and update jumanji path
  README.md
  requirements/requirements.txt
Labels: documentation, size/XS

#1016 fix: agent id obs spec dtype
  mava/wrappers/observation.py
Labels: size/S

#1018 feat: add dones to episode metrics
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/wrappers/episode_metrics.py
Labels: size/M

#1007 feat: change how networks are initialised by making use of hydra
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/network/cnn.yaml
  mava/configs/network/mlp.yaml
  mava/configs/network/rnn.yaml
  mava/evaluator.py
  mava/networks.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
Labels: size/L

#1015 chore: minor evaluator clean up
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/evaluator.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/utils/jax.py
Labels: size/L

#1021 fix: log step count on the x-axis of the neptune logger.
  mava/utils/logger.py
Labels: size/XS

#1022 Add return metrics for experiments and corresponding Hydra config option
  mava/configs/env/lbf.yaml
  mava/configs/env/rware.yaml
  mava/configs/env/smax.yaml
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
Labels: size/M

#1023 chore: remove neptune project argument from system level logger configs
  mava/configs/logger/ff_ippo.yaml
  mava/configs/logger/ff_mappo.yaml
  mava/configs/logger/rec_ippo.yaml
  mava/configs/logger/rec_mappo.yaml
Labels: maintenance, size/S

#1024 fix: initialize max_episode_return to negative infinity instead of zero for each algorithm
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
Labels: size/S

#1019 feat: Edit JaxMARL wrapper
  mava/configs/env/lbf.yaml
  mava/configs/env/mabrax.yaml
  mava/configs/env/rware.yaml
  mava/configs/env/scenario/10x10-3p-3f.yaml
  mava/configs/env/scenario/15x15-3p-5f.yaml
  mava/configs/env/scenario/15x15-4p-3f.yaml
  mava/configs/env/scenario/15x15-4p-5f.yaml
  mava/configs/env/scenario/2s-10x10-3p-3f.yaml
  mava/configs/env/scenario/2s-8x8-2p-2f-coop.yaml
  mava/configs/env/scenario/8x8-2p-2f-coop.yaml
  mava/configs/env/scenario/small-4ag.yaml
  mava/configs/env/scenario/tiny-2ag.yaml
  mava/configs/env/scenario/tiny-4ag-easy.yaml
  mava/configs/env/scenario/tiny-4ag.yaml
  mava/configs/env/smax.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/jaxmarl.py
Labels: size/L

#1030 Fix: fixes win_rate not being logged due to config change
  mava/evaluator.py
Labels: size/XS

#1028 feat: add matrax environment
  mava/configs/env/matrax.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/matrax.py
  requirements/requirements.txt
Labels: size/L

#1031 fix: mabrax wrapper
  mava/configs/env/mabrax.yaml
  mava/wrappers/jaxmarl.py
Labels: size/M

#1020 feat: system folders
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ppo/__init__.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/systems/ppo/types.py
  mava/types.py
  mava/utils/checkpointing.py
  mava/utils/jax.py
Labels: size/L

#1036 chore: update pre-commit config
  .pre-commit-config.yaml
  mava/utils/logger.py
  pyproject.toml
Labels: size/S

#1029 refactor: Remove agent's ID from the global_state
  mava/configs/env/mabrax.yaml
  mava/configs/env/smax.yaml
  mava/utils/make_env.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/observation.py
Labels: refactor, priority/high, size/L

#1039 Refactor the configs to mirror the structure of the python files
  mava/configs/default_ff_ippo.yaml
  mava/configs/default_ff_mappo.yaml
  mava/configs/default_rec_ippo.yaml
  mava/configs/default_rec_mappo.yaml
  mava/configs/system/ppo/ff_ippo.yaml
  mava/configs/system/ppo/ff_mappo.yaml
  mava/configs/system/ppo/rec_ippo.yaml
  mava/configs/system/ppo/rec_mappo.yaml
Labels: size/XS

#1040 feat: depend on marl-eval for json logger
  mava/utils/logger.py
  requirements/requirements.txt
Labels: enhancement, size/L

#1035 feat: Jumanji Connector wrapper
  mava/configs/env/connector.yaml
  mava/configs/env/scenario/con-10x10x5a.yaml
  mava/configs/env/scenario/con-15x15x10a.yaml
  mava/configs/env/scenario/con-5x5x3a.yaml
  mava/configs/env/scenario/con-7x7x5a.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/jumanji.py
Labels: size/L

#1041 Fix: dtype of agentid wrapper.
  mava/wrappers/observation.py
Labels: size/XS

#1044 fix: update Matrax's default episode length in keeping with literature
  mava/configs/env/matrax.yaml
Labels: size/XS

#1027 Feat : Gigastep wrapper
  mava/configs/env/gigastep.yaml
  mava/configs/env/scenario/hide_and_seek_5_vs_5_fobs.yaml
  mava/configs/env/scenario/hide_and_seek_5_vs_5_pobs.yaml
  mava/configs/env/scenario/waypoint_5_vs_5_fobs.yaml
  mava/configs/env/scenario/waypoint_5_vs_5_pobs.yaml
  mava/evaluator.py
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/gigastep.py
  mava/wrappers/jaxmarl.py
  requirements/requirements.txt
Labels: size/L

#1038 Feat/remove agent vmapping
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/evaluator.py
  mava/networks.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
Labels: size/L
