Repository instadeepai/Mava, pull requests merged in 2024-11, with the labels that each got.

#1121 More rware scenario configs
  mava/configs/env/scenario/large-4ag-hard.yaml
  mava/configs/env/scenario/large-4ag.yaml
  mava/configs/env/scenario/large-8ag-hard.yaml
  mava/configs/env/scenario/large-8ag.yaml
  mava/configs/env/scenario/medium-4ag-hard.yaml
  mava/configs/env/scenario/medium-4ag.yaml
  mava/configs/env/scenario/medium-6ag.yaml
  mava/configs/env/scenario/small-4ag-hard.yaml
  mava/configs/env/scenario/tiny-2ag-hard.yaml
  mava/configs/env/scenario/tiny-4ag-hard.yaml
  mava/configs/env/scenario/xlarge-4ag-hard.yaml
  mava/configs/env/scenario/xlarge-4ag.yaml
Labels: size/L

#1119 Fix quickstart notebook
  README.md
  examples/Quickstart.ipynb
  pyproject.toml
Labels: bug, size/L

#1123 Chore: Add asserts for number of envs divisible by number of minibatches
  mava/systems/mat/anakin/mat.py
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
Labels: size/S

#1120 Add vector connector wrapper
  mava/configs/env/vector-connector.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/jumanji.py
  test/integration_test.py
Labels: size/L

#1126 fix: mabrax requirement
  requirements/requirements.txt
Labels: size/XS

#1130 fix: limit timestep-pos-encoding to rec-Sable
  mava/networks/retention.py
Labels: bug, size/XS

#1127 Add Sable [Continuous actions]
  mava/configs/default/ff_sable.yaml
  mava/configs/default/rec_sable.yaml
  mava/networks/sable_network.py
  mava/networks/utils/sable/__init__.py
  mava/networks/utils/sable/decode.py
  mava/systems/sable/anakin/ff_sable.py
  mava/systems/sable/anakin/rec_sable.py
  test/integration_test.py
Labels: enhancement, size/L, benchmark complete

#1136 feat: update code owners
  .github/CODEOWNERS
Labels: maintenance, size/XS

#1088 Feat: sebulba ff_ippo
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/arch/anakin.yaml
  mava/configs/arch/sebulba.yaml
  mava/configs/default/ff_ippo_sebulba.yaml
  mava/configs/env/lbf_gym.yaml
  mava/configs/env/rware_gym.yaml
  mava/configs/env/smaclite_gym.yaml
  mava/evaluator.py
  mava/systems/__init__.py
  mava/systems/mat/anakin/mat.py
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/ppo/sebulba/ff_ippo.py
  mava/systems/ppo/types.py
  mava/systems/q_learning/anakin/rec_iql.py
  mava/systems/q_learning/anakin/rec_qmix.py
  mava/systems/sable/anakin/ff_sable.py
  mava/systems/sable/anakin/rec_sable.py
  mava/systems/sac/anakin/ff_hasac.py
  mava/systems/sac/anakin/ff_isac.py
  mava/systems/sac/anakin/ff_masac.py
  mava/types.py
  mava/utils/config.py
  mava/utils/jax_utils.py
  mava/utils/logger.py
  mava/utils/make_env.py
  mava/utils/network_utils.py
  mava/utils/sebulba.py
  mava/wrappers/__init__.py
  mava/wrappers/episode_metrics.py
  mava/wrappers/gym.py
  mava/wrappers/jaxmarl.py
  requirements/requirements.txt
Labels: size/XXL

#1103 Feat: MPE wrapper
  mava/configs/default/ff_hasac.yaml
  mava/configs/default/ff_ippo.yaml
  mava/configs/default/ff_isac.yaml
  mava/configs/default/ff_mappo.yaml
  mava/configs/default/ff_masac.yaml
  mava/configs/default/ff_sable.yaml
  mava/configs/default/mat.yaml
  mava/configs/default/rec_ippo.yaml
  mava/configs/default/rec_mappo.yaml
  mava/configs/default/rec_sable.yaml
  mava/configs/env/mpe.yaml
  mava/configs/env/scenario/simple_spread_10ag.yaml
  mava/configs/env/scenario/simple_spread_3ag.yaml
  mava/configs/env/scenario/simple_spread_5ag.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/jaxmarl.py
  requirements/requirements.txt
  test/integration_test.py
Labels: size/L

#1143 chore: move system name config setup inside run experiment
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/mat/anakin/mat.py
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/ppo/sebulba/ff_ippo.py
  mava/systems/q_learning/anakin/rec_iql.py
  mava/systems/q_learning/anakin/rec_qmix.py
  mava/systems/sable/anakin/ff_sable.py
  mava/systems/sable/anakin/rec_sable.py
  mava/systems/sac/anakin/ff_hasac.py
  mava/systems/sac/anakin/ff_isac.py
  mava/systems/sac/anakin/ff_masac.py
Labels: size/S

#1140 chore: only run integration tests after merge to dev
  .github/workflows/ci.yaml
  .github/workflows/integration_tests.yaml
  Dockerfile
Labels: size/M

#1145 fix: integration test workflow
  .github/workflows/integration_tests.yaml
Labels: size/XS
