Repository instadeepai/Mava, pull requests merged in 2024-07, with the labels that each got.

#1077 Chore: Connector Update
  mava/configs/env/connector.yaml
  mava/configs/env/scenario/con-10x10x10a.yaml
  mava/configs/env/scenario/con-10x10x5a.yaml
  mava/configs/env/scenario/con-15x15x10a.yaml
  mava/configs/env/scenario/con-15x15x23a.yaml
  mava/configs/env/scenario/con-5x5x3a.yaml
  mava/configs/env/scenario/con-7x7x5a.yaml
  mava/wrappers/jumanji.py
Labels: size/M

#1087 fix: remove weak types to prevent double compilation
  mava/wrappers/episode_metrics.py
  mava/wrappers/jaxmarl.py
Labels: size/S

#1081 feat: ruff formatter and linter
  .pre-commit-config.yaml
  examples/Quickstart.ipynb
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/distributions.py
  mava/evaluator.py
  mava/networks.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/systems/q_learning/rec_iql.py
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
  mava/utils/centralised_training.py
  mava/utils/checkpointing.py
  mava/utils/jax_utils.py
  mava/utils/logger.py
  mava/utils/make_env.py
  mava/utils/training.py
  mava/wrappers/__init__.py
  mava/wrappers/gigastep.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/jumanji.py
  pyproject.toml
  requirements/requirements-dev.txt
Labels: size/XXL

#1089 fix: unpack array shape when reshaping minibatches in mappo training
  mava/systems/ppo/ff_mappo.py
Labels: bug, size/XS

#1093 feat: upgrade supported python version
  .github/workflows/tests_linters.yaml
  Dockerfile
  README.md
  docs/DETAILED_INSTALL.md
  mava/wrappers/jumanji.py
  requirements/requirements.txt
Labels: size/L

#1095 chore: change all jax tree_map to tree.map
  examples/Quickstart.ipynb
  mava/advanced_usage/README.md
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/evaluator.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/systems/q_learning/rec_iql.py
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
  mava/utils/checkpointing.py
  mava/utils/jax_utils.py
  mava/utils/logger.py
  mava/wrappers/episode_metrics.py
  mava/wrappers/gigastep.py
Labels: size/L

#1070 feat: integration tests
  .github/workflows/tests_linters.yaml
  mava/configs/default_ff_ippo.yaml
  mava/configs/default_ff_isac.yaml
  mava/configs/default_ff_mappo.yaml
  mava/configs/default_ff_masac.yaml
  mava/configs/default_rec_ippo.yaml
  mava/configs/default_rec_iql.yaml
  mava/configs/default_rec_mappo.yaml
  mava/configs/network/continuous_mlp.yaml
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
  mava/utils/logger.py
  mava/wrappers/gigastep.py
  mava/wrappers/matrax.py
  test/conftest.py
  test/integration_test.py
Labels: test, maintenance, priority/low, size/L
