Repository instadeepai/Mava, pull requests merged in 2024-03, with the labels that each got.

#1037 Feat: Support Continuous environments with unvmapped Nets
  mava/configs/env/lbf.yaml
  mava/configs/network/mlp.yaml
  mava/configs/network/rnn.yaml
  mava/distributions.py
  mava/networks.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/jumanji.py
  mava/wrappers/matrax.py
Labels: size/L

#1053 fix: fix CNN torso to maintain batch and agent dimension
  mava/evaluator.py
  mava/networks.py
Labels: size/S

#1054 fix: steps per second count of the evaluator
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
Labels: bug, size/M

#1046 Feat: Custom global state for jumanji envs
  mava/configs/env/connector.yaml
  mava/configs/env/gigastep.yaml
  mava/configs/env/lbf.yaml
  mava/configs/env/mabrax.yaml
  mava/configs/env/matrax.yaml
  mava/configs/env/rware.yaml
  mava/configs/env/smax.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/jumanji.py
  mava/wrappers/matrax.py
  mava/wrappers/observation.py
Labels: size/L

#1013 feat: independent sac
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/default_ff_isac.yaml
  mava/configs/logger/ff_isac.yaml
  mava/configs/system/sac/ff_isac.yaml
  mava/evaluator.py
  mava/networks.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/systems/sac/__init__.py
  mava/systems/sac/ff_isac.py
  mava/systems/sac/types.py
  mava/utils/total_timestep_checker.py
Labels: size/XL

#1055 Generalise the evaluator factory to accept a custom apply function instead of enforcing network.apply
  mava/evaluator.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
Labels: size/M

#1062 Jumanji Wrapper: add a cast from Jumanji Observation to Mava Observation for consistent types in the observation_spec function
  mava/wrappers/jumanji.py
Labels: size/S

#1063 Chore: Rename jax file under utils folder
  examples/Quickstart.ipynb
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ppo/ff_ippo.py
  mava/systems/ppo/ff_mappo.py
  mava/systems/ppo/rec_ippo.py
  mava/systems/ppo/rec_mappo.py
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
  mava/utils/jax_utils.py
Labels: bug, maintenance, size/S

#1065 Make sure that config params passed to fbx.make_item_buffer are ints
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
Labels: size/S

#1066 fix: final return value for SAC systems
  mava/systems/sac/ff_isac.py
  mava/systems/sac/ff_masac.py
Labels: size/S

#1061 Recurrent IQL
  mava/configs/default_rec_iql.yaml
  mava/configs/logger/rec_iql.yaml
  mava/configs/network/rnn.yaml
  mava/configs/system/q_learning/rec_iql.yaml
  mava/distributions.py
  mava/networks.py
  mava/systems/q_learning/__init__.py
  mava/systems/q_learning/rec_iql.py
  mava/systems/q_learning/types.py
  mava/types.py
  mava/utils/jax_utils.py
  requirements/requirements.txt
Labels: size/XL

#1057 feat: cleaner wrapper
  mava/configs/env/cleaner.yaml
  mava/configs/env/scenario/clean-10x10x10a.yaml
  mava/configs/env/scenario/clean-15x15x15a.yaml
  mava/configs/env/scenario/clean-20x20x20a.yaml
  mava/configs/env/scenario/clean-30x30x30a.yaml
  mava/configs/env/scenario/clean-5x5x5a.yaml
  mava/utils/make_env.py
  mava/wrappers/__init__.py
  mava/wrappers/jumanji.py
Labels: size/L
