Repository instadeepai/Mava, pull requests merged in 2024-12, with the labels that each got.

#1147 fix: update ret_output shape
  mava/networks/retention.py
Labels: size/XS

#1124 chore: PPO system cleanup
  README.md
  examples/Quickstart.ipynb
  examples/advanced_usage/README.md
  examples/advanced_usage/ff_ippo_store_experience.py
  mava/evaluator.py
  mava/systems/mat/anakin/mat.py
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/ppo/sebulba/ff_ippo.py
  mava/systems/ppo/types.py
  mava/systems/sable/anakin/ff_sable.py
  mava/systems/sable/anakin/rec_sable.py
  mava/systems/sable/types.py
  mava/types.py
  mava/utils/sebulba.py
Labels: size/XL, benchmark complete

#1134 Feat: Support latest Jumanji version
  .github/workflows/ci.yaml
  examples/Quickstart.ipynb
  examples/advanced_usage/README.md
  examples/advanced_usage/ff_ippo_store_experience.py
  mava/configs/default/ff_ippo.yaml
  mava/configs/default/ff_mappo.yaml
  mava/configs/default/ff_sable.yaml
  mava/configs/default/mat.yaml
  mava/configs/default/rec_ippo.yaml
  mava/configs/default/rec_iql.yaml
  mava/configs/default/rec_mappo.yaml
  mava/configs/default/rec_sable.yaml
  mava/configs/env/connector.yaml
  mava/configs/env/lbf.yaml
  mava/configs/env/scenario/con-10x10x10a.yaml
  mava/configs/env/scenario/con-15x15x23a.yaml
  mava/configs/env/scenario/con-5x5x3a.yaml
  mava/configs/env/scenario/con-7x7x5a.yaml
  mava/configs/env/vector-connector.yaml
  mava/systems/mat/anakin/mat.py
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/q_learning/anakin/rec_iql.py
  mava/systems/q_learning/anakin/rec_qmix.py
  mava/systems/sable/anakin/ff_sable.py
  mava/systems/sable/anakin/rec_sable.py
  mava/systems/sac/anakin/ff_hasac.py
  mava/systems/sac/anakin/ff_isac.py
  mava/systems/sac/anakin/ff_masac.py
  mava/types.py
  mava/utils/make_env.py
  mava/wrappers/gigastep.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/jumanji.py
  mava/wrappers/matrax.py
  mava/wrappers/observation.py
  requirements/requirements.txt
Labels: size/L

#1108 feat: readme revamp
  README.md
  docs/CONTRIBUTING.md
  docs/DETAILED_INSTALL.md
  docs/images/algo_images/sable-arch.png
  docs/images/benchmark_results/connector.png
  docs/images/benchmark_results/lbf.png
  docs/images/benchmark_results/legend.jpg
  docs/images/benchmark_results/mabrax.png
  docs/images/benchmark_results/mpe.png
  docs/images/benchmark_results/rware.png
  docs/images/benchmark_results/smax.png
  docs/images/lbf_results/15x15-4p-3f_rec_mappo.png
  docs/images/lbf_results/2s-8x8-2p-2f-coop_rec_mappo.png
  docs/images/lbf_results/legend_rec_mappo.png
  docs/images/rware_results/ff_ippo/small-4ag.png
  docs/images/rware_results/ff_ippo/tiny-2ag.png
  docs/images/rware_results/ff_ippo/tiny-4ag.png
  docs/images/rware_results/ff_mappo/main_readme/legend.png
  docs/images/rware_results/ff_mappo/main_readme/small-4ag-1.png
  docs/images/rware_results/ff_mappo/main_readme/tiny-2ag-1.png
  docs/images/rware_results/ff_mappo/main_readme/tiny-4ag-1.png
  docs/images/rware_results/ff_mappo/small-4ag.png
  docs/images/rware_results/ff_mappo/tiny-2ag.png
  docs/images/rware_results/ff_mappo/tiny-4ag.png
  docs/images/rware_results/rec_ippo/small-4ag.png
  docs/images/rware_results/rec_ippo/tiny-2ag.png
  docs/images/rware_results/rec_ippo/tiny-4ag.png
  docs/images/rware_results/rec_mappo/small-4ag.png
  docs/images/rware_results/rec_mappo/tiny-2ag.png
  docs/images/rware_results/rec_mappo/tiny-4ag.png
  docs/images/smax_results/10m_vs_11m.png
  docs/images/smax_results/27m_vs_30m.png
  docs/images/smax_results/2s3z.png
  docs/images/smax_results/3s5z.png
  docs/images/smax_results/3s5z_vs_3s6z.png
  docs/images/smax_results/3s_vs_5z.png
  docs/images/smax_results/5m_vs_6m.png
  docs/images/smax_results/6h_vs_8z.png
  docs/images/smax_results/legend.png
  docs/images/speed_results/ff_mappo_speed_comparison.png
  docs/images/speed_results/mava_sps_results.png
  docs/images/speed_results/speed.png
  docs/jumanji_rware_comparison.md
  docs/smax_benchmark.md
  mava/systems/mat/README.md
  mava/systems/ppo/README.md
  mava/systems/q_learning/README.md
  mava/systems/sable/README.md
  mava/systems/sac/README.md
Labels: size/L
