Repository instadeepai/Mava, pull requests merged in 2024-01, with the labels that each got.

#979 chore: update README.md
  README.md
Labels: size/XS

#970 Feat: support SMAX
  mava/configs/env/smax.yaml
  mava/evaluator.py
  mava/logger.py
  mava/utils/logger_tools.py
  mava/utils/make_env.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/shared.py
Labels: enhancement, size/L, benchmark complete

#972 Enhancement: Make a `network.py` file
  mava/configs/default_ff_ippo.yaml
  mava/configs/default_ff_mappo.yaml
  mava/configs/default_rec_ippo.yaml
  mava/configs/default_rec_mappo.yaml
  mava/configs/network/mlp.yaml
  mava/configs/network/rnn.yaml
  mava/evaluator.py
  mava/networks.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
Labels: enhancement, size/XL

#973 Enhancement: change config to `DictConfig` instead of `Dict`
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/evaluator.py
  mava/networks.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/utils/logger_tools.py
  mava/utils/make_env.py
Labels: enhancement, size/XL

#984 fix: neptune tags need to be a list
  mava/utils/logger_tools.py
Labels: bug, size/XS

#974 Enhancement: Code cleanup
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/system/ff_ippo.yaml
  mava/configs/system/ff_mappo.yaml
  mava/configs/system/rec_ippo.yaml
  mava/configs/system/rec_mappo.yaml
  mava/evaluator.py
  mava/logger.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/types.py
  mava/utils/make_env.py
  mava/utils/multi_logger.py
  mava/utils/total_timestep_checker.py
Labels: enhancement, size/XXL

#938 Feat/add recurrent chunks
  mava/configs/logger/ff_ippo.yaml
  mava/configs/logger/ff_mappo.yaml
  mava/configs/logger/rec_ippo.yaml
  mava/configs/logger/rec_mappo.yaml
  mava/configs/system/rec_ippo.yaml
  mava/configs/system/rec_mappo.yaml
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/types.py
Labels: size/L, benchmark complete

#986 Fix: checkpointer
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/utils/checkpointing.py
  mava/utils/jax.py
Labels: bug, priority/high, size/L

#988 Fix: maintain and fix the quickstart notebook
  examples/Quickstart.ipynb
Labels: bug, maintenance, priority/high, size/L

#991 feat: add time_limit to jumanji env config
  mava/configs/env/lbf.yaml
  mava/configs/env/rware.yaml
  mava/utils/make_env.py
Labels: size/XS

#992 fix: use new vault api
  mava/advanced_usage/ff_ippo_store_experience.py
Labels: size/M

#989 feat: simplify logger
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/default_ff_ippo.yaml
  mava/configs/default_ff_mappo.yaml
  mava/configs/default_rec_ippo.yaml
  mava/configs/default_rec_mappo.yaml
  mava/configs/logger/base_logger.yaml
  mava/evaluator.py
  mava/logger.py
  mava/systems/ff_ippo.py
  mava/systems/ff_mappo.py
  mava/systems/rec_ippo.py
  mava/systems/rec_mappo.py
  mava/types.py
  mava/utils/logger.py
  mava/utils/multi_logger.py
Labels: size/XXL, priority/medium

#993 chore: minor changes to quickstart notebook
  examples/Quickstart.ipynb
Labels: size/S

#995 fix: bug fixes + add missing kwargs
  examples/Quickstart.ipynb
  mava/utils/checkpointing.py
  mava/utils/logger.py
  mava/utils/make_env.py
Labels: bug, maintenance, size/M, priority/high
