Repository instadeepai/Mava, pull requests merged in 2024-10, with the labels that each got.

#1101 refactor: update configs folder
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/default/ff_ippo.yaml
  mava/configs/default/ff_isac.yaml
  mava/configs/default/ff_mappo.yaml
  mava/configs/default/ff_masac.yaml
  mava/configs/default/rec_ippo.yaml
  mava/configs/default/rec_iql.yaml
  mava/configs/default/rec_mappo.yaml
  mava/configs/logger/ff_ippo.yaml
  mava/configs/logger/ff_isac.yaml
  mava/configs/logger/ff_mappo.yaml
  mava/configs/logger/ff_masac.yaml
  mava/configs/logger/logger.yaml
  mava/configs/logger/rec_ippo.yaml
  mava/configs/logger/rec_iql.yaml
  mava/configs/logger/rec_mappo.yaml
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/q_learning/anakin/rec_iql.py
  mava/systems/sac/anakin/ff_isac.py
  mava/systems/sac/anakin/ff_masac.py
  requirements/requirements.txt
  test/integration_test.py
Labels: size/L

#1102 Refactor networks
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/network/cnn.yaml
  mava/configs/network/continuous_mlp.yaml
  mava/configs/network/mlp.yaml
  mava/configs/network/rcnn.yaml
  mava/configs/network/rnn.yaml
  mava/networks/__init__.py
  mava/networks/base.py
  mava/networks/distributions.py
  mava/networks/heads.py
  mava/networks/torsos.py
Labels: size/L

#1104 feat: set the action head automatically
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/configs/default/ff_ippo.yaml
  mava/configs/default/ff_isac.yaml
  mava/configs/default/ff_mappo.yaml
  mava/configs/default/ff_masac.yaml
  mava/configs/network/cnn.yaml
  mava/configs/network/continuous_mlp.yaml
  mava/configs/network/mlp.yaml
  mava/configs/network/rcnn.yaml
  mava/configs/network/rnn.yaml
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/sac/anakin/ff_isac.py
  mava/systems/sac/anakin/ff_masac.py
  mava/utils/network_utils.py
  test/integration_test.py
Labels: size/L

#1112 feat: uv for github actions
  .github/workflows/tests_linters.yaml
  .pre-commit-config.yaml
Labels: size/M

#1111 feat: smaller networks for tests
  test/__init__.py
  test/conftest.py
  test/integration_test.py
  test/utils.py
Labels: size/L

#1114 Fix lbf and rware obs spec types
  mava/wrappers/gigastep.py
  mava/wrappers/jumanji.py
Labels: bug, size/XS

#1116 fix: fix logging during evaluation for JaxMARL envs
  mava/evaluator.py
Labels: size/XS

#1109 feat: switch to pyproject.toml
  mava/__init__.py
  mava/advanced_usage/ff_ippo_store_experience.py
  mava/evaluator.py
  mava/networks/torsos.py
  mava/types.py
  mava/utils/logger.py
  mava/utils/make_env.py
  mava/version.py
  mava/wrappers/gigastep.py
  mava/wrappers/jaxmarl.py
  pyproject.toml
  setup.py
Labels: size/L

#1107 Add MAT
  mava/configs/default/mat.yaml
  mava/configs/network/transformer.yaml
  mava/configs/system/mat/mat.yaml
  mava/networks/attention.py
  mava/networks/base.py
  mava/networks/mat_network.py
  mava/networks/torsos.py
  mava/networks/utils/__init__.py
  mava/networks/utils/mat/__init__.py
  mava/networks/utils/mat/decode.py
  mava/systems/mat/anakin/mat.py
  mava/systems/mat/types.py
  mava/types.py
  mava/utils/checkpointing.py
  pyproject.toml
  requirements/requirements.txt
  test/conftest.py
  test/integration_test.py
Labels: size/XXL

#1115 feat: updated dockerfile
  .dockerignore
  Dockerfile
  Makefile
Labels: size/M
