Repository instadeepai/Mava, pull requests merged in 2025-04, with the labels that each got.

#1167 fix: small rec_iql fixes
  mava/configs/system/q_learning/rec_iql.yaml
  mava/systems/q_learning/sebulba/rec_iql.py
Labels: size/XS

#1165 feat: rec sable sebulba
  mava/configs/default/rec_sable_sebulba.yaml
  mava/systems/sable/sebulba/rec_sable.py
  mava/utils/sebulba/pipelines.py
  mava/wrappers/gym.py
Labels: size/XL

#1166 feat: logger refactor
  .gitignore
  mava/configs/logger/logger.yaml
  mava/evaluator.py
  mava/systems/mat/anakin/mat.py
  mava/systems/ppo/anakin/ff_ippo.py
  mava/systems/ppo/anakin/ff_mappo.py
  mava/systems/ppo/anakin/rec_ippo.py
  mava/systems/ppo/anakin/rec_mappo.py
  mava/systems/ppo/sebulba/ff_ippo.py
  mava/systems/ppo/sebulba/rec_ippo.py
  mava/systems/q_learning/anakin/rec_iql.py
  mava/systems/q_learning/anakin/rec_qmix.py
  mava/systems/q_learning/sebulba/rec_iql.py
  mava/systems/sable/anakin/ff_sable.py
  mava/systems/sable/anakin/rec_sable.py
  mava/systems/sac/anakin/ff_hasac.py
  mava/systems/sac/anakin/ff_isac.py
  mava/systems/sac/anakin/ff_masac.py
  mava/types.py
  mava/utils/logger.py
  mava/wrappers/episode_metrics.py
  mava/wrappers/gigastep.py
  mava/wrappers/gym.py
  mava/wrappers/jaxmarl.py
  mava/wrappers/jumanji.py
  mava/wrappers/matrax.py
Labels: size/XL

#1174 fix: matrax env metrics when using global state
  mava/wrappers/matrax.py
Labels: size/XS

#1173 fix(ippo-store-experience): adapt for changes in the codebase
  examples/advanced_usage/ff_ippo_store_experience.py
Labels: size/L
