Repository instadeepai/Mava, pull requests merged in 2025-03, with the labels that each got.

#1164 Fix: pin gymansium and flax versions
  requirements/requirements.txt
Labels: size/XS

#1156 Feat: sebulba recurrent ippo
  mava/configs/default/rec_ippo_sebulba.yaml
  mava/systems/ppo/sebulba/rec_ippo.py
Labels: size/XL

#1148 Feat Sebulba recurrent IQL
  mava/configs/default/rec_iql_sebulba.yaml
  mava/configs/system/q_learning/rec_iql.yaml
  mava/evaluator.py
  mava/systems/ppo/sebulba/ff_ippo.py
  mava/systems/ppo/sebulba/rec_ippo.py
  mava/systems/q_learning/anakin/rec_iql.py
  mava/systems/q_learning/anakin/rec_qmix.py
  mava/systems/q_learning/sebulba/rec_iql.py
  mava/systems/q_learning/types.py
  mava/utils/config.py
  mava/utils/sebulba.py
  mava/utils/sebulba/pipelines.py
  mava/utils/sebulba/rate_limiters.py
  mava/utils/sebulba/utils.py
  mava/wrappers/gym.py
Labels: size/XXL
